(* Reuse exact closed IBP rules only after matching the full ordered
   denominator definitions, external frame, cuts, measures and prescriptions. *)
BeginPackage["FeynFacet`"];
ReuseIntegralReduction::usage="ReuseIntegralReduction[families,targets,reduction] reuses closed IBP rules for exactly identical integral-family definitions, allowing family-name changes. It verifies source target coverage and never interprets an unresolved target as a master.";
ApplyIntegralReduction::usage="ApplyIntegralReduction[coefficientRows,reduction] substitutes a closed exact integral reduction into sparse external-coefficient rows and cancels the resulting master coefficients with exact rational arithmetic. It retains the row labels and never evaluates or expands the master integrals.";
TransformIntegralReductionEquations::usage="TransformIntegralReductionEquations[families,reduction] rewrites retained exact reduction identities in new complete inverse-propagator coordinates. Uncovered new targets remain to be solved; the transformed identities can be supplied as ExtraEquations to the common IBP solver.";
EliminateKnownIntegralRules::usage="EliminateKnownIntegralRules[rows,targets,rules] substitutes supplied exact closed linear integral identities into every sparse equation. It retains all remaining columns, including integrals outside the requested targets, and returns the residual equations and required target images. The identities are assumed established by their producer; this operation does not prove new physical relations or discard unresolved columns.";
Begin["`Private`"];
EliminateKnownIntegralRules[rows_List,targets_List,rules_List]:=Catch[Module[
 {lhs,parsed,objects,columns,masters,output,images,coefficients,rationalQ},
 If[!AllTrue[rows,AssociationQ]||!MatchQ[rules,{(_Rule)...}]||
   !AllTrue[targets,MatchQ[#,_FeynCalc`GLI]&],cutFamilyFail["SparseIntegralEquationsAndExactRulesRequired"]];
 lhs=First/@rules;
 If[!DuplicateFreeQ[lhs]||!AllTrue[lhs,MatchQ[#,_FeynCalc`GLI]&],
   cutFamilyFail["DistinctIntegralRuleLeftSidesRequired"]];
 parsed=linearIntegralSum/@(Last/@rules);
 If[!AllTrue[parsed,linearIntegralSumQ[#]&&Together[#["Remainder"]]===0&],
   cutFamilyFail["HomogeneousLinearKnownIntegralRulesRequired"]];
 objects=Union[Flatten[Keys/@Lookup[parsed,"Terms",{}]]];
 If[Intersection[objects,lhs]=!={},cutFamilyFail["ClosedKnownIntegralRulesRequired"]];
 columns=Union[targets,Flatten[Keys/@rows],objects];
 If[!AllTrue[columns,MatchQ[#,_FeynCalc`GLI]&],cutFamilyFail["IntegralEquationColumnsRequired"]];
 coefficients=Join[Flatten[Values/@rows],Flatten[Values/@Lookup[parsed,"Terms",{}]]];
 rationalQ[value_]:=Module[{v=Together[value],variables},
   variables=DeleteDuplicates[Cases[v,_Symbol,{0,Infinity}]];
   FreeQ[v,_Real|_Complex|_FeynCalc`GLI]&&PolynomialQ[Numerator[v],variables]&&PolynomialQ[Denominator[v],variables]];
 If[!AllTrue[DeleteDuplicates[coefficients],rationalQ],cutFamilyFail["ExactRationalKnownIntegralCoefficientsRequired"]];
 masters=Complement[columns,lhs];
 output=FeynFacet`ApplyIntegralReduction[AssociationThread[Range[Length[rows]],rows],
   <|"Rules"->rules,"Masters"->masters|>];
 If[!AssociationQ[output],cutFamilyFail["KnownIntegralEliminationFailed",<|"Cause"->output|>]];
 output=DeleteDuplicates[DeleteCases[Values[output],<||>]];
 images=targets/.Dispatch[rules];
 <|"Format"->"FeynFacet-ResidualIntegralEquations","Rows"->output,
   "Targets"->Union[Cases[images,_FeynCalc`GLI,{0,Infinity}]],"OriginalTargets"->targets,
   "TargetImages"->images,"KnownRules"->rules,"OriginalEquationCount"->Length[rows],
   "OriginalColumnCount"->Length[Union[Flatten[Keys/@rows]]],
   "ResidualColumnCount"->Length[Union[Flatten[Keys/@output]]],
   "Scope"->"Exact substitution of supplied closed identities into all equations. Every remaining integral column is retained; no master minimality or new physical relation is inferred."|>
],"CutFamily"];
ReuseIntegralReduction[families:{__Association},targets_List,reduction_Association]:=Catch[Module[
 {old=Lookup[reduction,"Families",{}],signature,positions,newToOld,oldToNew,mapped,known,rules,
  masters,images,missing,selected},
 If[!ListQ[old]||!ListQ[Lookup[reduction,"Rules",None]]||!ListQ[Lookup[reduction,"Masters",None]],
  cutFamilyFail["ClosedIntegralReductionRequired"]];
 signature[family_]:={Rest[List@@family["Topology"]],family["MeasurePrefactor"],
  Lookup[family,"Cuts",{}],Lookup[family,"TimeDirection",None],family["Definition"],
  Lookup[family,"OrdinaryPropagatorPrescriptions",None]};
 positions=Table[FirstPosition[signature/@old,signature[family],Missing[],{1},Heads->False],
  {family,families}];
 If[AnyTrue[positions,MissingQ],Return[reuseIntegralReductionCoordinates[families,targets,reduction]]];
 selected=old[[Flatten[positions]]];
 newToOld=MapThread[#1["Topology"][[1]]->#2["Topology"][[1]]&,{families,selected}];
 oldToNew=Reverse/@newToOld;
 If[!DuplicateFreeQ[First/@oldToNew],cutFamilyFail["DistinctReusedFamilyNamesRequired"]];
 mapped=targets/.newToOld;rules=reduction["Rules"];masters=reduction["Masters"];
 known=Union[First/@rules,masters];missing=Complement[mapped,known];
 If[missing=!={},cutFamilyFail["ReusedReductionTargetCoverageIncomplete",<|"MissingTargets"->missing|>]];
 images=mapped/.Dispatch[rules];
 If[Complement[DeleteDuplicates[Cases[images,_FeynCalc`GLI,{0,Infinity}]],masters]=!={},
  cutFamilyFail["ReusedReductionNotClosed"]];
 If[Complement[DeleteDuplicates[First/@Cases[images,_FeynCalc`GLI,{0,Infinity}]],
   First/@oldToNew]=!={},cutFamilyFail["AdditionalReusedMasterFamiliesRequired"]];
 Join[KeyDrop[reduction,{"Families","Rules","Masters","Targets"}],<|
  "Families"->families,"Targets"->targets,
  "Rules"->Thread[targets->(images/.oldToNew)],
  "Masters"->DeleteDuplicates[Cases[images/.oldToNew,_FeynCalc`GLI,{0,Infinity}]],
  "ReductionReuse"-><|"FamilyRules"->newToOld,"ExactDefinitionsVerified"->True,
   "AllTargetsCovered"->True,"ClosedOnDeclaredMasters"->True|>|>]
],"CutFamily"];
ApplyIntegralReduction[rows_Association,reduction_Association]:=Catch[Module[
  {rules,masters,images=<||>,local,objects,coefficients,output,terms,result,final,parsed,offset=0},
 rules=Lookup[reduction,"Rules",None];masters=Lookup[reduction,"Masters",None];
 If[!MatchQ[rules,{(_Rule)...}]||!ListQ[masters]||!AllTrue[Values[rows],AssociationQ],
  cutFamilyFail["ClosedReductionAndSparseCoefficientRowsRequired"]];
 Do[
  parsed=linearIntegralSum[Last[rule]];
  If[!linearIntegralSumQ[parsed]||Together[parsed["Remainder"]]=!=0,
   cutFamilyFail["LinearIntegralReductionRulesRequired",<|"Integral"->First[rule],"Cause"->parsed|>]];
  objects=Keys[parsed["Terms"]];
  If[!ContainsAll[masters,objects],cutFamilyFail["IntegralReductionNotClosed"]];
  AssociateTo[images,First[rule]->parsed["Terms"]],
 {rule,rules}];
 Do[If[!KeyExistsQ[images,master],AssociateTo[images,master-><|master->1|>]],{master,masters}];
 output=Association@KeyValueMap[Function[{name,row},
  If[!AllTrue[Keys[row],KeyExistsQ[images,#]&],cutFamilyFail["IntegralCoefficientTargetNotReduced",<|"Row"->name|>]];
  terms=Flatten[KeyValueMap[Function[{integral,coefficient},
    KeyValueMap[#1->coefficient #2&,images[integral]]],row],1];
  result=If[terms==={},<||>,Merge[terms,Total]];
   name->result],rows];
  (* Cancel one batch, allowing the backend to deduplicate and split large
     inputs. A native-process launch for every sparse equation is prohibitive. *)
  coefficients=FeynFacet`CancelRationalCoefficients[Flatten[Values/@Values[output]]];
  If[!ListQ[coefficients],cutFamilyFail["ReducedCoefficientCancellationFailed",<|"Cause"->coefficients|>]];
  output=Map[Function[row,Module[{n=Length[row],values},
    If[n===0,Return[<||>]];
    values=coefficients[[offset+Range[n]]];offset+=n;
    Select[AssociationThread[Keys[row],values],#=!=0&]]],output];
 final=Lookup[reduction,"FinalBasisReduction",None];
 If[final=!=None,
  If[!AssociationQ[final]||KeyExistsQ[final,"FinalBasisReduction"],
   cutFamilyFail["OneExplicitFinalMasterBasisReductionRequired"]];
  output=FeynFacet`ApplyIntegralReduction[output,final]];
 output
],"CutFamily"];
reuseIntegralReductionCoordinates[families_,targets_,reduction_]:=Catch[Module[
 {old=reduction["Families"],oldRules=Dispatch[reduction["Rules"]],known,maps=<||>,reverse=<||>,
  selected=<||>,local,candidate,choice,images,needed,oldMasters,back,backRules,output,newMasters,byOld,reduceImage},
 known=AssociationThread[Union[First/@reduction["Rules"],reduction["Masters"]],ConstantArray[True,Length[Union[First/@reduction["Rules"],reduction["Masters"]]]]];
 byOld=Association[(#["Topology"][[1]]->#)&/@old];
 Do[
  local=Select[targets,#[[1]]===family["Topology"][[1]]&];If[local==={},Continue[]];
  choice=None;
  Do[
   candidate=FeynFacet`MapIntegralFamilyCoordinates[local,family,donor];
   If[!AssociationQ[candidate],Continue[]];
   needed=Union[Flatten[Keys/@Values[candidate["IntegralImages"]]]];
   If[AllTrue[needed,KeyExistsQ[known,#]&],choice=candidate;Break[]],
  {donor,old}];
  If[choice===None,cutFamilyFail["NoCoveredIntegralCoordinateMap",<|"Family"->family["Topology"][[1]]|>]];
  maps=Join[maps,choice["IntegralImages"]];
  AssociateTo[selected,choice["RepresentativeDefinition"]["Topology"][[1]]->family],
 {family,families}];
 reduceImage[image_]:=Total[KeyValueMap[#2(#1/.oldRules)&,image]];
 images=reduceImage/@maps;
 oldMasters=Union[Flatten[Cases[Values[images],_FeynCalc`GLI,{0,Infinity}]]];
 If[!ContainsAll[reduction["Masters"],oldMasters],cutFamilyFail["CoordinateReusedReductionNotClosed"]];
 Do[
  local=Select[oldMasters,#[[1]]===name&];
  If[!KeyExistsQ[selected,name],cutFamilyFail["AdditionalCoordinateMasterFamilyRequired"]];
  back=FeynFacet`MapIntegralFamilyCoordinates[local,byOld[name],selected[name]];
  If[!AssociationQ[back],cutFamilyFail["ReverseMasterCoordinateMapRequired",<|"Cause"->back|>]];
  reverse=Join[reverse,back["IntegralImages"]],
 {name,Union[First/@oldMasters]}];
 backRules=Dispatch[Normal[Map[Total[KeyValueMap[Times,#]]&,reverse]]];
 output=Thread[targets->(Lookup[images,targets]/.backRules)];
 newMasters=Union[Cases[Last/@output,_FeynCalc`GLI,{0,Infinity}]];
 Join[KeyDrop[reduction,{"Families","Rules","Masters","Targets"}],<|
  "Families"->families,"Targets"->targets,"Rules"->output,"Masters"->newMasters,
  "ReductionReuse"-><|"ExactCoordinateChangesVerified"->True,"AllTargetsCovered"->True,
    "ClosedOnDeclaredMasters"->True,"ForwardIntegralImages"->maps,"ReverseMasterImages"->reverse|>|>]
],"CutFamily"];
TransformIntegralReductionEquations[families_List,reduction_Association]:=Catch[Module[
 {columns,old,images=<||>,proofs={},local,choice,candidate,rows,terms,coefficients,toTerms},
 If[!ListQ[Lookup[reduction,"Rules",None]]||!ListQ[Lookup[reduction,"Families",None]],
  cutFamilyFail["ExactRetainedReductionIdentitiesRequired"]];
 old=reduction["Families"];
 columns=Union[Cases[reduction["Rules"],_FeynCalc`GLI,{0,Infinity}]];
 Do[
  local=Select[columns,#[[1]]===donor["Topology"][[1]]&];If[local==={},Continue[]];
  choice=None;
  Do[
   candidate=FeynFacet`MapIntegralFamilyCoordinates[local,donor,family];
   If[AssociationQ[candidate],choice=candidate;Break[]],
  {family,SortBy[families,If[#["Topology"][[1]]===donor["Topology"][[1]],0,1]&]}];
  If[choice===None,cutFamilyFail["RetainedReductionCoordinateMapRequired",<|"Family"->donor["Topology"][[1]]|>]];
  images=Join[images,choice["IntegralImages"]];AppendTo[proofs,KeyDrop[choice,"IntegralImages"]],
 {donor,old}];
 toTerms[expression_]:=Flatten[Map[Function[integral,
   KeyValueMap[#1->Coefficient[expression,integral]#2&,images[integral]]],
  DeleteDuplicates[Cases[expression,_FeynCalc`GLI,{0,Infinity}]]],1];
 rows=Map[Function[rule,
  terms=Join[Normal[images[First[rule]]],(First[#]->-Last[#]&/@toTerms[Last[rule]])];
  coefficients=Map[Cancel[Together[#]]&,Merge[terms,Total]];
  Select[coefficients,#=!=0&]],reduction["Rules"]];
 <|"Format"->"FeynFacet-TransformedIntegralReductionEquations","Rows"->DeleteDuplicates[DeleteCases[rows,<||>]],
   "CoordinateMaps"->proofs,"SourceReductionWorkspace"->Lookup[reduction,"Workspace",None],
   "ExactIdentityScope"->"The retained identities in explicitly verified inverse-propagator coordinates. New target coverage is not asserted."|>
],"CutFamily"];
End[];EndPackage[];
