(* Complete virtual scalar densities enter the same affine IBP algebra.
   Ordinary prescriptions are retained. No forward-cut theorem is invoked. *)
BeginPackage["FeynFacet`"];
DecomposeVirtualLoopIntegrands::usage="DecomposeVirtualLoopIntegrands[values,loops,external,kinematicRules,request] converts full-D scalar virtual integrands to explicit GLI coefficient rules and complete ordinary integral families. Equal denominator products share one family across named tensor structures. Ordinary prescriptions and the original density are retained.";
DecomposeCutLoopIntegrands::usage="DecomposeCutLoopIntegrands[values,cutDefinition,virtualLoops,request] decomposes scalar loop corrections on explicitly directed unit cuts without removing ordinary prescriptions. It retains the cut definition, adds the declared virtual integration momenta, and uses the same prescribed-product numerator algebra as virtual-only decomposition. The default additional virtual measure is d^D ell per loop; request may explicitly set VirtualLoopMeasurePrefactor. Dependent original denominators fail pending a prescription-preserving partial fraction reduction.";
Begin["`Private`"];
(* Source-level algebra AFTER the caller has proved the external prescription
   limit of this exact source. Virtual denominators never enter this partial
   fraction step. The componentwise nonincrease of external powers makes each
   new term the original rational product times a bounded cut polynomial. *)
cutLoopExternalPartialFractions[values_Association,input_Association,virtualLoops_List,request_Association:<||>]:=Catch[Module[
 {definition,kin,routed,objects,cores={},props={},aliases={},replacement,standard,
  external,virtual,desc,core,index,unit,power,polynomials,products,unitRules,basis,
  free,variables,restricted,partials,output,rewritten,assumptions,checks},
 definition=FeynFacet`CreateCutIntegralDefinition[input];
 If[!AssociationQ[definition]||definition["MeasurementCutIndices"]=!={}||
   definition["ParticleCutIndices"]=!=definition["CutIndices"]||
   (KeyExistsQ[input,"CutPowers"]&&input["CutPowers"]=!=ConstantArray[1,Length[definition["CutIndices"]]]),
  cutFamilyFail["OriginalUnitParticleCutsRequired"]];
 kin=definition["Topology"][[5]];assumptions=Lookup[request,"Assumptions",definition["Assumptions"]];
 routed=Map[FeynCalc`FCI[#]/.Lookup[input,"MomentumConservationRules",{}]&,values];
 objects=DeleteDuplicates[Cases[routed,_FeynCalc`FeynAmpDenominator,Infinity]];
 replacement=Table[
  standard=FeynCalc`ToSFAD[object];
  If[Head[standard]=!=FeynCalc`FeynAmpDenominator,cutFamilyFail["ExplicitOrdinaryPropagatorProductRequired"]];
  external=1;virtual={};
  Do[
   If[!FreeQ[prop,Alternatives@@virtualLoops],AppendTo[virtual,prop];Continue[]];
   desc=propagatorDescriptor[prop,kin];
   If[!AssociationQ[desc]||!IntegerQ[desc["Power"]]||desc["Power"]<=0,
    cutFamilyFail["PositiveExternalPropagatorPowersRequired"]];
   core=Factor[FeynCalc`ExpandScalarProduct[desc["UnitCore"]]/.kin];
   index=FirstPosition[cores,core,Missing[],{1},Heads->False];
   If[MissingQ[index],AppendTo[cores,core];
    AppendTo[props,FeynCalc`FeynAmpDenominator[FeynCalc`GenericPropagatorDenominator[core,{1,1}]]];
    AppendTo[aliases,Unique["externalLoopDenominator"]];index={Length[cores]}];
   external*=aliases[[First[index]]]^desc["Power"],{prop,List@@standard}];
  object->external If[virtual==={},1,FeynCalc`FeynAmpDenominator@@virtual],{object,objects}];
 If[cores==={},Return[<|"Values"->routed,"PartialFractions"-><||>,"ExternalPolynomials"->{},
    "PowersNeverIncreased"->True,"VirtualPrescriptionsChanged"->False|>,Module]];
 polynomials=Map[FeynFacet`PolynomialCoefficientRules[#/.replacement,aliases]&,routed];
 If[AnyTrue[Values[polynomials],FailureQ],cutFamilyFail["PolynomialExternalProductsRequired"]];
 products=DeleteDuplicates[Flatten[(First/@#)&/@Values[polynomials],1]];
 unitRules=FeynFacet`UnitCutScalarProductRules[definition];
 If[!ListQ[unitRules],cutFamilyFail["AffineParticleUnitCutsRequired"]];
 basis=definition["LoopScalarProducts"];free=Complement[basis,First/@unitRules];
 variables=Table[Unique["externalCutCoordinate"],{Length[free]}];
 restricted=(cores/.unitRules)/.Thread[free->variables];
 If[!FreeQ[restricted,_FeynCalc`Pair],cutFamilyFail["CompleteExternalUnitCutCoordinatesRequired"]];
 partials=Association@Table[powers->FeynFacet`PartialFractionAffineDenominators[
   restricted,powers,variables,<|"Assumptions"->assumptions|>],{powers,products}];
 If[AnyTrue[Values[partials],FailureQ],cutFamilyFail["ExternalUnitCutPartialFractionsFailed",
   <|"Cause"->SelectFirst[Values[partials],FailureQ]|>]];
 checks=KeyValueMap[Function[{powers,result},
   AllTrue[result["Terms"],And@@Thread[#["Powers"]<=powers]&]&&
   TrueQ[FullSimplify[result["ValidityConditions"],Assumptions->assumptions]]],partials];
 If[!AllTrue[checks,TrueQ],cutFamilyFail["NonincreasingExternalPowersAndNonzeroDivisorsRequired"]];
 rewritten=Association@KeyValueMap[Function[{powers,result},powers->Total[
   #["Coefficient"]Times@@MapThread[Power,{props,#["Powers"]}]&/@result["Terms"]]],partials];
 output=Map[Total[(Last[#]rewritten[First[#]])&/@#]&,polynomials];
 <|"Values"->output,"PartialFractions"->partials,"ExternalPolynomials"->cores,
   "PowersNeverIncreased"->True,"VirtualPrescriptionsChanged"->False,
   "Scope"->"Rational identities on original unit particle cuts, conditional on the caller's source-specific external prescription limit. External factors are represented with a common positive prescription only after that limit. Every virtual factor and unrestricted denominator polynomial is retained; no claim is made for dotted descendants."|>
],"CutFamily"];
DecomposeVirtualLoopIntegrands[values_Association,loops:{__Symbol},external:{__Symbol},
 kin_List,request_Association:<||>]:=decomposePrescribedLoopIntegrands[values,loops,external,kin,request,None];
DecomposeCutLoopIntegrands[values_Association,input_Association,virtualLoops:{__Symbol},request_Association:<||>]:=
 Catch[Module[{definition,top,loops,routed,measure},
  definition=FeynFacet`CreateCutIntegralDefinition[input];
  If[!AssociationQ[definition]||definition["CutIndices"]==={},cutFamilyFail["ExplicitDirectedUnitCutDefinitionRequired"]];
  top=definition["Topology"];loops=Join[top[[3]],virtualLoops];
  If[!DuplicateFreeQ[Join[loops,top[[4]]]],cutFamilyFail["DistinctVirtualCutAndExternalMomentaRequired"]];
  routed=Map[FeynCalc`FCI[#]/.Lookup[input,"MomentumConservationRules",{}]&,values];
  measure=definition["MeasurePrefactor"]Lookup[request,"VirtualLoopMeasurePrefactor",1];
  definition=FeynFacet`CreateCutIntegralDefinition[Join[definition,<|"Topology"->ReplacePart[top,3->loops],
    "MeasurePrefactor"->measure|>]];
  If[!AssociationQ[definition],cutFamilyFail["MixedCutLoopDefinitionRequired",<|"Cause"->definition|>]];
  decomposePrescribedLoopIntegrands[routed,loops,top[[4]],top[[5]],Join[request,<|"MeasurePrefactor"->measure|>],definition]
 ],"CutFamily"];
decomposePrescribedLoopIntegrands[values_Association,loops_List,external_List,kin_List,request_Association,cutDefinition_]:=Catch[Module[
 {internal,objects,aliases,polynomials,products,product,families={},records=<||>,top,converted,
  base,complete,mapped,master,rules,basis,scalar,coordinateRules,powers,coefficients,
  output=<||>,targets={},family,prefix,assumptions,name,positions,allProducts,
  unitPropagators,propagatorPowers,standard,unit,index,cutProps={},cuts={},cutCount=0,allProps,allPowers},
 If[!DuplicateFreeQ[Join[loops,external]]||!AllTrue[kin,MatchQ[#,_Rule]&],
  cutFamilyFail["DistinctVirtualLoopAndExternalMomentaRequired"]];
 internal=FeynCalc`FCI/@values;
 If[AssociationQ[cutDefinition],
  cutProps=cutDefinition["Topology"][[2,cutDefinition["CutIndices"]]];cutCount=Length[cutProps];
  cuts=MapIndexed[Join[#1,<|"Index"->First[#2]|>]&,cutDefinition["Cuts"]]];
 If[!FreeQ[internal,_FeynCalc`Eps|_FeynCalc`DiracGamma|_FeynCalc`LorentzIndex|_Real|_Failure],
  cutFamilyFail["FullDimensionScalarVirtualDensityRequired"]];
 objects=DeleteDuplicates[Cases[Values[internal],_FeynCalc`FeynAmpDenominator,{0,Infinity}]];
 aliases=Table[Unique["virtualDenominator"],{Length[objects]}];
 polynomials=FeynFacet`PolynomialCoefficientRules[#/.Thread[objects->aliases],aliases]&/@internal;
 If[AnyTrue[Values[polynomials],FailureQ],cutFamilyFail["PolynomialPrescribedDenominatorProductsRequired"]];
 allProducts=DeleteDuplicates[Flatten[First/@#&/@Values[polynomials],1]];
 prefix=Lookup[request,"FamilyNamePrefix","VirtualLoopFamily"];assumptions=Lookup[request,"Assumptions",True];
 Do[
  product=Times@@MapThread[Power,{objects,powers}];
  unitPropagators={};propagatorPowers={};
  Do[
   If[powers[[j]]===0,Continue[]];
   standard=FeynCalc`ToSFAD[objects[[j]]];
   If[Head[standard]=!=FeynCalc`FeynAmpDenominator||
      !AllTrue[List@@standard,MatchQ[#,_FeynCalc`StandardPropagatorDenominator|_FeynCalc`GenericPropagatorDenominator]&],
    cutFamilyFail["ExplicitOrdinaryPropagatorProductRequired"]];
   Do[
    unit=ReplacePart[prop,{Length[prop],1}->1];
    index=FirstPosition[unitPropagators,unit,Missing[],{1},Heads->False];
    If[MissingQ[index],AppendTo[unitPropagators,unit];
      AppendTo[propagatorPowers,powers[[j]]Last[prop][[1]]],
      propagatorPowers[[First[index]]]+=powers[[j]]Last[prop][[1]]],
   {prop,List@@standard}],
  {j,Length[objects]}];
  name=Symbol["FeynFacet`IntegralFamilies`"<>prefix<>ToString[Length[families]+1]];
  allProps=Join[cutProps,FeynCalc`FeynAmpDenominator/@unitPropagators];
  allPowers=Join[ConstantArray[1,cutCount],propagatorPowers];
  top=FeynCalc`FCTopology[name,allProps,
   loops,external,FeynCalc`FCI[kin],{}];
  complete=FeynFacet`CompleteAffineIntegralTopology[top];
  If[!MatchQ[complete,_FeynCalc`FCTopology],Throw[complete,"CutFamily"]];
  master=FeynCalc`GLI[name,PadRight[allPowers,Length[complete[[2]]]]];
  mapped=master;
  family=If[AssociationQ[cutDefinition],
   FeynFacet`CreateCutIntegralFamily[Join[cutDefinition,<|"Topology"->complete,"Cuts"->cuts|>]],
   FeynFacet`CreateLoopIntegralFamily[<|"Topology"->complete,
    "MeasurePrefactor"->Lookup[request,"MeasurePrefactor",1],"Assumptions"->assumptions|>]];
  If[!AssociationQ[family],Throw[family,"CutFamily"]];
  AppendTo[families,family];AssociateTo[records,powers-><|"Family"->family,"Master"->master,
   "Coefficient"->(mapped/.master->1)|>],
 {powers,allProducts}];
 KeyValueMap[Function[{label,terms},
  coefficients=<||>;
  Do[
   {powers,scalar}=List@@term;family=records[[Key[powers]]]["Family"];
   master=records[[Key[powers]]]["Master"];
   scalar=FeynCalc`ExpandScalarProduct[scalar]/.FeynCalc`FCI[kin];
   scalar=scalar/.family["ScalarProductRules"];
   coordinateRules=FeynFacet`PolynomialCoefficientRules[scalar,family["DenominatorVariables"]];
   If[FailureQ[coordinateRules]||!FreeQ[coordinateRules,_FeynCalc`Pair],
    cutFamilyFail["PolynomialVirtualNumeratorRequired"]];
   Do[
    base=FeynCalc`GLI[master[[1]],master[[2]]-First[rule]];
    If[cutCount>0&&!AllTrue[Take[base[[2]],cutCount],#>0&],Continue[]];
    AssociateTo[coefficients,base->(Lookup[coefficients,base,0]+
     records[[Key[powers]]]["Coefficient"]Last[rule])],
   {rule,coordinateRules}],
  {term,terms}];
  coefficients=Select[Factor/@coefficients,#=!=0&];
  targets=Join[targets,Keys[coefficients]];
  AssociateTo[output,label->coefficients]
 ],polynomials];
 <|"Format"->If[AssociationQ[cutDefinition],"FeynFacet-CutLoopIntegralFamilies","FeynFacet-VirtualIntegralFamilies"],"FormatVersion"->1,
  "Families"->families,"CoefficientRules"->output,"Targets"->DeleteDuplicates[targets],
  "SourceValues"->values,"LoopMomenta"->loops,"ExternalMomenta"->external,
  "KinematicRules"->kin,"OrdinaryPrescriptionLimitEstablished"->False,
  "LoopMeasure"->"Integral measure is declared by MeasurePrefactor; generated amplitude factors remain in CoefficientRules."|>
],"CutFamily"];
End[];EndPackage[];
