(* Seed selection is a heuristic search envelope. It never deletes
   terms from exact IBP equations or certifies master minimality. *)
BeginPackage["FeynFacet`"];
PlanCutIBPSeeds::usage="PlanCutIBPSeeds[family,targets,request] chooses sector-local IBP seeds from the union of actual numerator/dot downsets. Untouched subsectors start with unit cuts and a reduced inherited numerator rank. All requested targets remain seeds. These bounds select equations, not integral columns, and are not a sufficiency theorem.";
FindCutIBPPredecessorSeeds::usage="FindCutIBPPredecessorSeeds[family,frontier,existingSeeds,request] finds unseeded admissible predecessors whose exact momentum-IBP equations contain a frontier integral with nonzero coefficient. FrontierNeighborDepth optionally adds up to three shells of harder dot/numerator intermediates before the incidence search. It uses the actual IBP shifts and does not promote new positive denominator slots unless explicitly allowed.";
ReduceCutIntegralsToBasis::usage="ReduceCutIntegralsToBasis[families,targets,candidates,request] grows exact momentum-IBP seeds around nonpreferred target remainders. SamplingPoints guide a bounded search; only a final exact Kira reduction whose target images lie in the supplied candidate span is accepted. A failed search is not a nonexistence or master-minimality certificate.";
ConstructUnitCutMasterCandidates::usage="ConstructUnitCutMasterCandidates[families,targets,request] enumerates candidate integrals with all mandatory cuts at unit power, bounded powers of ordinary denominators already present in targets, and bounded auxiliary numerator rank. No new positive auxiliary denominator is introduced. Sufficiency and independence are not asserted; ReduceCutIntegralsToBasis can establish the required exact target span.";
Begin["`Private`"];
cutIBPPositiveSector[powers_,cuts_]:=Complement[Flatten[Position[powers,_Integer?Positive,{1}]],cuts];
cutIBPNumeratorDegree[powers_]:=-Total[Select[powers,Negative]];
cutIBPProfile[family_,powers_]:=Module[{particle,measurement,ordinary},
 particle=Lookup[Select[family["Cuts"],#["Type"]==="Particle"&],"Index",{}];
 measurement=Complement[family["CutIndices"],particle];
 ordinary=Complement[Range[Length[powers]],family["CutIndices"]];
 {Total[(powers[[particle]]-1)],Total[(powers[[measurement]]-1)],
  Total[Max[0,#-1]&/@powers[[ordinary]]],cutIBPNumeratorDegree[powers]}
];
PlanCutIBPSeeds[family_Association,targets:{__FeynCalc`GLI},request_Association:<||>]:=Catch[Module[
 {name,count,cuts,direct,sectors,include,groups,seedRows,indices,choices,rank,parents,
  absent,base,rows,seedTag=Unique["sectorSeed"],reports={},limit,generated},
 If[!MemberQ[{"FeynFacet-CutIntegralFamily","FeynFacet-LoopIntegralFamily"},Lookup[family,"Format",None]],
  cutFamilyFail["TypedIBPSeedFamilyRequired"]];
 name=family["Topology"][[1]];count=Length[family["Topology"][[2]]];cuts=family["CutIndices"];
 If[!AllTrue[targets,#[[1]]===name&&Length[#[[2]]]===count&&VectorQ[#[[2]],IntegerQ]&&
    AllTrue[#[[2,cuts]],#>0&]&],cutFamilyFail["AdmissibleTargetSeedIntegralsRequired"]];
 include=Lookup[request,"IncludeSubsectors",True];limit=Lookup[request,"MaximumSeeds",1000000];
 If[!MemberQ[{True,False},include]||!IntegerQ[limit]||limit<Length[targets],
  cutFamilyFail["IBPSeedSelectionBoundsRequired"]];
 groups=GroupBy[targets,cutIBPPositiveSector[#[[2]],cuts]&];
 direct=Keys[groups];
 sectors=If[include,Union[Flatten[Subsets/@direct,1]],direct];
 generated=0;
 seedRows=Reap[Do[
  If[KeyExistsQ[groups,sector],
   rows=DeleteDuplicates[Flatten[Table[
    choices=Map[If[#>0,Range[1,#],Range[#,0]]&,master[[2]]];
    Tuples[choices],{master,groups[[Key[sector]]]}],1]];
   rank=Max[cutIBPNumeratorDegree[#[[2]]]&/@groups[[Key[sector]]]],
   parents=Select[targets,ContainsAll[cutIBPPositiveSector[#[[2]],cuts],sector]&];
   rank=Max[1,Max[Map[cutIBPNumeratorDegree[#[[2]]]-
     (Length[cutIBPPositiveSector[#[[2]],cuts]]-Length[sector])&,parents]]];
   absent=Complement[Range[count],Join[cuts,sector]];
   base=ReplacePart[ConstantArray[0,count],Thread[Join[cuts,sector]->1]];
   rows=Map[ReplacePart[base,Thread[absent->(-#)]]&,cutSeedCompositionsUpTo[rank,Length[absent]]]
  ];
  generated+=Length[rows];
  If[generated>limit,cutFamilyFail["IBPSeedSelectionSizeLimit",<|"MaximumSeeds"->limit|>]];
  AppendTo[reports,<|"OrdinarySector"->sector,"DirectTargetSector"->KeyExistsQ[groups,sector],
    "NumeratorDegreeLimit"->rank,"SeedCount"->Length[rows]|>];
  Scan[Sow[FeynCalc`GLI[name,#],seedTag]&,rows],
 {sector,sectors}],seedTag][[2]];
 seedRows=If[seedRows==={},{},DeleteDuplicates[First[seedRows]]];
 If[!ContainsAll[seedRows,targets],cutFamilyFail["TargetSeedCoverageFailed"]];
 <|"Format"->"FeynFacet-IBPSeedPlan","FormatVersion"->1,"Family"->name,
  "Seeds"->seedRows,"TargetCount"->Length[targets],"SeedCount"->Length[seedRows],
  "Sectors"->reports,"Method"->"UnionOfTargetDownsetsWithSectorLocalDotBounds",
  "Scope"->"An initial equation-selection heuristic. Exact equation columns are unrestricted, and sufficiency requires target reduction into the chosen span."|>
],"CutFamily"];

FindCutIBPPredecessorSeeds[family_Association,frontier:{__FeynCalc`GLI},existing_List,
 request_Association:<||>]:=Catch[Module[
 {count,name,cuts,operators,indices,zero,raw,shiftRows,shifts,allowed,known,candidates,
  nu,coefficients,limit,searchFrontier,depth,neighbors,positive,negative,
  compatible=Lookup[request,"CutCompatibleVectors",None],
  ordinary=Lookup[request,"IncludeOrdinaryVectors",True],tag=Unique["ibpPredecessor"]},
 count=Length[family["Topology"][[2]]];name=family["Topology"][[1]];cuts=family["CutIndices"];
 If[!AllTrue[Join[frontier,existing],MatchQ[#,_FeynCalc`GLI]&&#[[1]]===name&&
   Length[#[[2]]]===count&&VectorQ[#[[2]],IntegerQ]&&AllTrue[#[[2,cuts]],#>0&]&],
  cutFamilyFail["SameFamilyIBPFrontierAndSeedsRequired"]];
 allowed=Lookup[request,"AllowedPositiveIndices",Union[Flatten[
   Flatten[Position[#[[2]],_Integer?Positive,{1}]]&/@Join[frontier,existing]]]];
 limit=Lookup[request,"MaximumCandidates",100000];
 If[!VectorQ[allowed,IntegerQ[#]&&1<=#<=count&]||!ContainsAll[allowed,cuts]||
  !IntegerQ[limit]||limit<1,cutFamilyFail["IBPPredecessorBoundsRequired"]];
 depth=Lookup[request,"FrontierNeighborDepth",0];
 If[!IntegerQ[depth]||!Between[depth,{0,3}],
  cutFamilyFail["IBPFrontierNeighborDepthRequired"]];
 searchFrontier=frontier;
 Do[
  neighbors=Flatten[Map[Function[master,
    positive=Intersection[allowed,Flatten[Position[master[[2]],_Integer?Positive,{1}]]];
    negative=Complement[Range[count],positive];
    Join[(FeynCalc`GLI[name,master[[2]]+UnitVector[count,#]]&/@positive),
      (FeynCalc`GLI[name,master[[2]]-UnitVector[count,#]]&/@negative)]
  ],searchFrontier],1];
  searchFrontier=Union[searchFrontier,neighbors],
 {depth}];
 If[!MemberQ[{True,False},ordinary],cutFamilyFail["BooleanOrdinaryIBPVectorSelectionRequired"]];
 operators=If[ordinary,cutIBPOperators[family],{}];
 If[compatible=!=None,
  If[!AssociationQ[compatible]||Lookup[compatible,"Format",None]=!="FeynFacet-CutCompatibleIBPVectors"||
    !TrueQ[Lookup[compatible,"ExactIndividualTangencyVerified",False]]||compatible["Family"]=!=family,
   cutFamilyFail["MatchingCertifiedPredecessorVectorsRequired"]];
  operators=Join[operators,compatible["Operators"]]];
 indices=Table[Unique["integralPower"],{count}];
 shiftRows=cutIBPShiftRows[family,operators,indices];
 shifts=GroupBy[Flatten[shiftRows,1],First->Last];
 known=AssociationThread[existing,ConstantArray[True,Length[existing]]];
 candidates=Reap[Do[
  KeyValueMap[Function[{shift,expressions},
   nu=master[[2]]-shift;
   If[AllTrue[nu[[cuts]],#>0&]&&ContainsAll[allowed,Flatten[Position[nu,_Integer?Positive,{1}]]]&&
     !KeyExistsQ[known,FeynCalc`GLI[name,nu]],
    coefficients=expressions/.Thread[indices->nu];
    If[AnyTrue[coefficients,Cancel[Together[#]]=!=0&],
     Sow[FeynCalc`GLI[name,nu],tag]]]],shifts],
 {master,searchFrontier}],tag][[2]];
 candidates=If[candidates==={},{},DeleteDuplicates[First[candidates]]];
 If[Length[candidates]>limit,cutFamilyFail["IBPPredecessorCountLimit",<|"Count"->Length[candidates]|>]];
 <|"Format"->"FeynFacet-IBPPredecessorSeeds","Seeds"->candidates,
  "SeedCount"->Length[candidates],"Profiles"->(cutIBPProfile[family,#[[2]]]&/@candidates),
  "AllowedPositiveIndices"->allowed,"SearchFrontier"->searchFrontier,"FrontierNeighborDepth"->depth,
  "Scope"->"Admissible unseeded inverse-incidence candidates. Choosing a sufficient subset remains an adaptive reduction problem."|>
],"CutFamily"];
ConstructUnitCutMasterCandidates[families:{__Association},targets:{__FeynCalc`GLI},
 request_Association:<||>]:=Catch[Module[
 {maximum=Lookup[request,"MaximumOrdinaryPower",1],rank=Lookup[request,"MaximumAuxiliaryNumeratorDegree",1],
  limit=Lookup[request,"MaximumCandidates",100000],candidates={},name,count,cuts,local,positive,auxiliary,
  numerators,powers,one,sectorLocal=Lookup[request,"SectorLocalNumerators",True],active},
 If[!IntegerQ[maximum]||!Between[maximum,{1,3}]||!IntegerQ[rank]||!Between[rank,{0,3}]||
   !MemberQ[{True,False},sectorLocal]||!IntegerQ[limit]||limit<1,cutFamilyFail["BoundedUnitCutCandidateRequestRequired"]];
 Do[name=family["Topology"][[1]];count=Length[family["Topology"][[2]]];cuts=family["CutIndices"];
  local=Select[targets,#[[1]]===name&];If[local==={},Continue[]];
  If[!AllTrue[local,Length[#[[2]]]===count&&VectorQ[#[[2]],IntegerQ]&&
    AllTrue[#[[2,cuts]],#>0&]&],cutFamilyFail["AdmissibleUnitCutCandidateTargetsRequired"]];
  positive=Complement[Union[Flatten[Flatten[Position[#[[2]],_Integer?Positive,{1}]]&/@local]],cuts];
  Do[powers=ReplacePart[ConstantArray[0,count],Thread[cuts->1]];
   powers=ReplacePart[powers,Thread[positive->denominators]];
   active=If[sectorLocal,Pick[positive,Unitize[denominators],1],positive];
   auxiliary=Complement[Range[count],Join[cuts,active]];
   numerators=cutSeedCompositionsUpTo[rank,Length[auxiliary]];
   If[Length[candidates]+Length[numerators]>limit,cutFamilyFail["UnitCutCandidateCountLimit"]];
   Do[one=FeynCalc`GLI[name,ReplacePart[powers,Thread[auxiliary->(-numerator)]]];AppendTo[candidates,one],
    {numerator,numerators}],{denominators,Tuples[Range[0,maximum],Length[positive]]}],
 {family,families}];
 <|"Masters"->Union[candidates],"MaximumOrdinaryPower"->maximum,"MaximumAuxiliaryNumeratorDegree"->rank,
  "SectorLocalNumerators"->sectorLocal,"TargetSpanEstablished"->False,"MasterMinimalityEstablished"->False|>
],"CutFamily"];
ReduceCutIntegralsToBasis[families:{__Association},targets:{__FeynCalc`GLI},
 candidates:{__FeynCalc`GLI},request_Association]:=Catch[Module[
 {work,points,limit,seedLimit,seeds=<||>,plans,local,rows={},generated,samples,frontier,
  added,more,iteration,history={},exact,images,unmatched,allSeeds,preferred=Union[candidates],
  name,depth,record,byName,trialDepth,tangentVectors=<||>,tangent,
  vectorMethod=Lookup[request,"IBPVectorMethod","Ordinary"],
  protection=Lookup[request,"CutProtection","All"]},
 work=Lookup[request,"WorkingDirectory",None];points=Lookup[request,"SamplingPoints",None];
 limit=Lookup[request,"MaximumSeedIterations",5];seedLimit=Lookup[request,"MaximumSeeds",100000];
 If[!StringQ[work]||!MatchQ[points,{{(_Rule)..}..}]||!IntegerQ[limit]||limit<1||
   !MemberQ[{"Ordinary","CutCompatible","Mixed"},vectorMethod]||!MemberQ[{"All","Particle"},protection]||
   !IntegerQ[seedLimit]||seedLimit<1,cutFamilyFail["BoundedSampledBasisSearchRequestRequired"]];
 byName=Association[(#["Topology"][[1]]->#)&/@families];
 If[!DuplicateFreeQ[First[#["Topology"]]&/@families]||
   !ContainsAll[Keys[byName],First/@Join[targets,preferred]],cutFamilyFail["DistinctKnownBasisFamiliesRequired"]];
 Do[name=family["Topology"][[1]];local=Select[Union[targets,preferred],#[[1]]===name&];
  plans=If[local==={},<|"Seeds"->{}|>,PlanCutIBPSeeds[family,local,<|"MaximumSeeds"->seedLimit|>]];
  If[!AssociationQ[plans],cutFamilyFail["BasisSearchSeedPlanRequired",<|"Cause"->plans|>]];
  AssociateTo[seeds,name->plans["Seeds"]],{family,families}];
 If[vectorMethod=!="Ordinary",Do[
  tangent=FeynFacet`ConstructCutCompatibleIBPVectors[family,<|
   "Degree"->Lookup[request,"CutVectorDegree",1],"ProtectedIndices"->
    If[protection==="All",family["CutIndices"],family["ParticleCutIndices"]]|>];
  If[!AssociationQ[tangent],cutFamilyFail["CertifiedPolynomialCutVectorsRequired",<|"Cause"->tangent|>]];
  AssociateTo[tangentVectors,family["Topology"][[1]]->tangent],{family,families}]];
 added=seeds;
 Do[
  If[Total[Length/@Values[seeds]]>seedLimit,cutFamilyFail["BasisSearchSeedLimit",<|"History"->history|>]];
  Do[name=family["Topology"][[1]];If[added[name]==={},Continue[]];
   generated=If[vectorMethod==="CutCompatible",<|"Rows"->{}|>,FeynFacet`GenerateCutIBPEquations[family,added[name]]];
   If[!AssociationQ[generated],cutFamilyFail["BasisSearchExactEquationsRequired",<|"Cause"->generated|>]];
   rows=Join[rows,generated["Rows"]];
   If[vectorMethod=!="Ordinary",
    tangent=FeynFacet`GenerateCutCompatibleIBPEquations[family,added[name],tangentVectors[name]];
    If[!AssociationQ[tangent],cutFamilyFail["CutCompatibleBasisEquationsRequired",<|"Cause"->tangent|>]];
    rows=Join[rows,tangent["Rows"]]],{family,families}];
  If[iteration===1,rows=Join[rows,Lookup[request,"ExtraEquations",{}]]];
  Print["BASIS SEED SEARCH ",iteration," SEEDS ",Total[Length/@Values[seeds]]," ROWS ",Length[rows]];
  samples=FeynFacet`SampleCutIBPEquations[rows,targets,families,<|
   "WorkingDirectory"->work<>"/Sample"<>IntegerString[iteration,10,3],
   "PreferredMasterIntegrals"->preferred,"Points"->points,
   "RequireClosedExport"->False,
   "ComputeRemainderRank"->False,
   "Threads"->Lookup[request,"Threads",1],"Prime"->Lookup[request,"Prime",2147483647]|>];
  If[!AssociationQ[samples],cutFamilyFail["BasisSearchSamplesRequired",<|"Cause"->samples|>]];
  frontier=Union[Flatten[Lookup[samples["Samples"],"NonpreferredIntegralColumns"],1]];
  record=<|"Iteration"->iteration,"SeedCount"->Total[Length/@Values[seeds]],
    "EquationCount"->Length[rows],"UnmatchedTargetColumns"->frontier,
    "SampleRanks"->Lookup[samples["Samples"],"TargetRemainderRank"]|>;
  AppendTo[history,record];
  Print["BASIS SEARCH REMAINING COLUMNS ",Length[frontier]];
  (* A sampled pole or an incomplete point-specific export can leave a
     conservative remainder at another point. One closing point justifies an
     exact attempt; only the closed rational result can accept the span. *)
  If[frontier==={}||AnyTrue[samples["Samples"],TrueQ[#["AllTargetsInPreferredSpanAtPoint"]]&],
   exact=FeynFacet`KiraReduction[families,targets,
    Join[KeyTake[request,{"Threads","HomogeneousScale","RationalSolver","PrintTimings"}],<|
     "WorkingDirectory"->work<>"/Exact"<>IntegerString[iteration,10,3],
     "SeedIntegrals"->{},"ExtraEquations"->rows,"PreferredMasterIntegrals"->preferred|>]];
   If[!AssociationQ[exact],cutFamilyFail["ExactCandidateBasisReductionRequired",<|"Cause"->exact|>]];
   images=targets/.Dispatch[exact["Rules"]];
   unmatched=Complement[DeleteDuplicates[Cases[images,_FeynCalc`GLI,{0,Infinity}]],preferred];
   If[unmatched==={},Return[Join[exact,<|"CandidateMasterBasis"->preferred,
     "TargetSpanVerifiedExactly"->True,"SeedSearchHistory"->history|>],Module]];
   frontier=unmatched
  ];
  If[iteration===limit,Break[]];
  added=<||>;depth=Min[2,Quotient[iteration-1,2]];
  Do[
  Do[name=family["Topology"][[1]];local=Select[frontier,#[[1]]===name&];
   more=If[local==={},<|"Seeds"->{}|>,FindCutIBPPredecessorSeeds[family,local,seeds[name],
     <|"FrontierNeighborDepth"->trialDepth,"MaximumCandidates"->seedLimit,
       "IncludeOrdinaryVectors"->(vectorMethod=!="CutCompatible"),
       "CutCompatibleVectors"->Lookup[tangentVectors,name,None]|>]];
   If[!AssociationQ[more],cutFamilyFail["BasisSearchPredecessorsRequired",<|"Cause"->more|>]];
   AssociateTo[added,name->more["Seeds"]];AssociateTo[seeds,name->Union[seeds[name],more["Seeds"]]],
   {family,families}];
  If[Total[Length/@Values[added]]>0,Break[]],{trialDepth,depth,2}];
  If[Total[Length/@Values[added]]===0,cutFamilyFail["BasisSearchNeedsBroaderRegion",<|"History"->history|>]],
 {iteration,limit}];
 cutFamilyFail["CandidateBasisSearchIncomplete",<|"History"->history,
  "Scope"->"Bounded IBP search failed; no assertion of irreducibility or master minimality."|>]
],"CutFamily"];
End[];EndPackage[];
