<|"Family" -> "CF254", "BlockPair" -> {9, 8}, "Variables" -> {x, y}, 
 "Regulator" -> eps, "Dimensions" -> <|"E" -> {2, 4, 4}, "C" -> {2, 2, 2}, 
   "BBar" -> {2, 4, 2}|>, 
 "E" -> {<|"Factor" -> -1 + x, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 0, 0}|>, 
   <|"Factor" -> x, "MaximumPower" -> 1, "EpsilonDependent" -> False, 
    "Degrees" -> {1, 0, 0}|>, <|"Factor" -> -1 + 2*x - y, 
    "MaximumPower" -> 1, "EpsilonDependent" -> False, 
    "Degrees" -> {1, 1, 0}|>, <|"Factor" -> -3 + 2*x + y, 
    "MaximumPower" -> 1, "EpsilonDependent" -> False, 
    "Degrees" -> {1, 1, 0}|>, <|"Factor" -> -1 + 2*x + y, 
    "MaximumPower" -> 1, "EpsilonDependent" -> False, 
    "Degrees" -> {1, 1, 0}|>, <|"Factor" -> 1 + 2*x + y, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 1, 0}|>, 
   <|"Factor" -> -1 - 8*x + 4*x^2 - 2*y - y^2, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {2, 2, 0}|>, 
   <|"Factor" -> 3 + 4*x^2 + 2*y - y^2, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {2, 2, 0}|>, 
   <|"Factor" -> -1 + 6*x + 2*x*y + y^2, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 2, 0}|>, 
   <|"Factor" -> 1 + y, "MaximumPower" -> 1, "EpsilonDependent" -> False, 
    "Degrees" -> {0, 1, 0}|>, <|"Factor" -> 1 - 2*x + y, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 1, 0}|>, 
   <|"Factor" -> -3 - 4*x^2 - 2*y + y^2, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {2, 2, 0}|>, 
   <|"Factor" -> 1 + 8*x - 4*x^2 + 2*y + y^2, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {2, 2, 0}|>}, 
 "C" -> {<|"Factor" -> -1 + x, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 0, 0}|>, 
   <|"Factor" -> x, "MaximumPower" -> 1, "EpsilonDependent" -> False, 
    "Degrees" -> {1, 0, 0}|>, <|"Factor" -> -3 + 2*x + y, 
    "MaximumPower" -> 1, "EpsilonDependent" -> False, 
    "Degrees" -> {1, 1, 0}|>, <|"Factor" -> 1 + 2*x + y, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 1, 0}|>, 
   <|"Factor" -> -1 + 6*x + 2*x*y + y^2, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 2, 0}|>, 
   <|"Factor" -> -3 + 4*x + 4*x^2 - 2*y + 4*x*y + y^2, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {2, 2, 0}|>, 
   <|"Factor" -> 1 + y, "MaximumPower" -> 1, "EpsilonDependent" -> False, 
    "Degrees" -> {0, 1, 0}|>}, 
 "BBar" -> {<|"Factor" -> 1 + eps, "MaximumPower" -> 1, 
    "EpsilonDependent" -> True, "Degrees" -> {0, 0, 1}|>, 
   <|"Factor" -> 1 + 4*eps, "MaximumPower" -> 1, "EpsilonDependent" -> True, 
    "Degrees" -> {0, 0, 1}|>, <|"Factor" -> -1 + x, "MaximumPower" -> 2, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 0, 0}|>, 
   <|"Factor" -> -1 + 2*x - y, "MaximumPower" -> 2, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 1, 0}|>, 
   <|"Factor" -> -1 + 2*x + y, "MaximumPower" -> 2, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 1, 0}|>, 
   <|"Factor" -> 1 + 2*x + y, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 1, 0}|>, 
   <|"Factor" -> 3 + 4*x^2 + 2*y - y^2, "MaximumPower" -> 2, 
    "EpsilonDependent" -> False, "Degrees" -> {2, 2, 0}|>, 
   <|"Factor" -> -1 + 6*x + 2*x*y + y^2, "MaximumPower" -> 2, 
    "EpsilonDependent" -> False, "Degrees" -> {1, 2, 0}|>, 
   <|"Factor" -> -3 + 4*x + 4*x^2 - 2*y + 4*x*y + y^2, "MaximumPower" -> 2, 
    "EpsilonDependent" -> False, "Degrees" -> {2, 2, 0}|>, 
   <|"Factor" -> -9 - 11*eps + 12*x + 24*eps*x + 12*x^2 + 12*eps*x^2 - 6*y - 
      6*eps*y + 12*x*y + 16*eps*x*y + 3*y^2 + 5*eps*y^2, "MaximumPower" -> 2, 
    "EpsilonDependent" -> True, "Degrees" -> {2, 2, 1}|>, 
   <|"Factor" -> x, "MaximumPower" -> 1, "EpsilonDependent" -> False, 
    "Degrees" -> {1, 0, 0}|>, <|"Factor" -> -3 + 2*x + y, 
    "MaximumPower" -> 1, "EpsilonDependent" -> False, 
    "Degrees" -> {1, 1, 0}|>, <|"Factor" -> 1 + y, "MaximumPower" -> 1, 
    "EpsilonDependent" -> False, "Degrees" -> {0, 1, 0}|>}, 
 "InfinityDegrees" -> 
  <|"E" -> {{{{-1, -1, -1, -1}, {-1, -1, -1, -1}, {-1, -1, -1, -1}, 
       {-1, -1, -1, -1}}, {{0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, 
       {0, 0, 0, 0}}}, {{{0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, 
       {0, 0, 0, 0}}, {{-1, -1, -1, -1}, {-1, -1, -1, -1}, {-1, -1, -1, -1}, 
       {-1, -1, -1, -1}}}}, "C" -> {{{{-1, -1}, {-1, -1}}, {{0, 0}, {0, 0}}}, 
     {{{0, 0}, {0, 0}}, {{-1, -1}, {-1, -1}}}}, 
   "BBar" -> {{{{-1, -1}, {-1, -1}, {-1, -1}, {-1, -1}}, 
      {{0, 0}, {0, 0}, {0, 0}, {0, 0}}}, {{{0, 0}, {0, 0}, {0, 0}, {0, 0}}, 
      {{-1, -1}, {-1, -1}, {-1, -1}, {-1, -1}}}}|>|>
