{<|"Position" -> 9, "Method" -> "WholeTogether", "Seconds" -> 0.195666, 
  "InputBytes" -> 4279848, "OutputBytes" -> 72136, "InputTerms" -> 323, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 9, "Method" -> "WholeSimplify", 
  "Seconds" -> 1.490184, "InputBytes" -> 4279848, "OutputBytes" -> 25256, 
  "InputTerms" -> 323, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 9, "Method" -> "TogetherThenSimplify", 
  "Seconds" -> 0.70615, "InputBytes" -> 4279848, "OutputBytes" -> 25256, 
  "InputTerms" -> 323, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 9, "Method" -> "SimplifyThenTogether", 
  "Seconds" -> 0.427058, "InputBytes" -> 4279848, "OutputBytes" -> 72136, 
  "InputTerms" -> 323, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 9, "Method" -> "HistoricalCollect", 
  "Seconds" -> 0.383772, "InputBytes" -> 4279848, "OutputBytes" -> 25256, 
  "InputTerms" -> 323, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 9, 
  "Method" -> "TogetherThenHistoricalCollect", "Seconds" -> 0.199672, 
  "InputBytes" -> 4279848, "OutputBytes" -> 25256, "InputTerms" -> 323, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 6, "Method" -> "WholeTogether", 
  "Seconds" -> 0.324555, "InputBytes" -> 6438104, "OutputBytes" -> 74048, 
  "InputTerms" -> 363, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 6, "Method" -> "WholeSimplify", 
  "Seconds" -> 1.527857, "InputBytes" -> 6438104, "OutputBytes" -> 22848, 
  "InputTerms" -> 363, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 6, "Method" -> "TogetherThenSimplify", 
  "Seconds" -> 0.835661, "InputBytes" -> 6438104, "OutputBytes" -> 22848, 
  "InputTerms" -> 363, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 6, "Method" -> "SimplifyThenTogether", 
  "Seconds" -> 0.480082, "InputBytes" -> 6438104, "OutputBytes" -> 74048, 
  "InputTerms" -> 363, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 6, "Method" -> "HistoricalCollect", 
  "Seconds" -> 0.488738, "InputBytes" -> 6438104, "OutputBytes" -> 22848, 
  "InputTerms" -> 363, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 6, 
  "Method" -> "TogetherThenHistoricalCollect", "Seconds" -> 0.278255, 
  "InputBytes" -> 6438104, "OutputBytes" -> 22848, "InputTerms" -> 363, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 44, "Method" -> "WholeTogether", 
  "Seconds" -> 0.247407, "InputBytes" -> 4909856, "OutputBytes" -> 75936, 
  "InputTerms" -> 323, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 44, "Method" -> "WholeSimplify", 
  "Seconds" -> 1.626308, "InputBytes" -> 4909856, "OutputBytes" -> 23520, 
  "InputTerms" -> 323, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 44, 
  "Method" -> "TogetherThenSimplify", "Seconds" -> 0.77565, 
  "InputBytes" -> 4909856, "OutputBytes" -> 23520, "InputTerms" -> 323, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 44, 
  "Method" -> "SimplifyThenTogether", "Seconds" -> 0.485122, 
  "InputBytes" -> 4909856, "OutputBytes" -> 75936, "InputTerms" -> 323, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 44, "Method" -> "HistoricalCollect", 
  "Seconds" -> 0.495337, "InputBytes" -> 4909856, "OutputBytes" -> 23520, 
  "InputTerms" -> 323, "OutputTerms" -> 1, "RemainingFractionVariables" -> 
   {}, "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 44, 
  "Method" -> "TogetherThenHistoricalCollect", "Seconds" -> 0.251841, 
  "InputBytes" -> 4909856, "OutputBytes" -> 23520, "InputTerms" -> 323, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 80, "Method" -> "WholeTogether", 
  "Seconds" -> 0.101974, "InputBytes" -> 2367872, "OutputBytes" -> 10552, 
  "InputTerms" -> 1, "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 80, "Method" -> "WholeSimplify", 
  "Seconds" -> 0.312, "InputBytes" -> 2367872, "OutputBytes" -> 4560, 
  "InputTerms" -> 1, "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 80, 
  "Method" -> "TogetherThenSimplify", "Seconds" -> 0.225869, 
  "InputBytes" -> 2367872, "OutputBytes" -> 4560, "InputTerms" -> 1, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 80, 
  "Method" -> "SimplifyThenTogether", "Seconds" -> 0.150411, 
  "InputBytes" -> 2367872, "OutputBytes" -> 10480, "InputTerms" -> 1, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 80, "Method" -> "HistoricalCollect", 
  "Seconds" -> 0.140297, "InputBytes" -> 2367872, "OutputBytes" -> 4560, 
  "InputTerms" -> 1, "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 80, 
  "Method" -> "TogetherThenHistoricalCollect", "Seconds" -> 0.098234, 
  "InputBytes" -> 2367872, "OutputBytes" -> 4560, "InputTerms" -> 1, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 73, "Method" -> "WholeTogether", 
  "Seconds" -> 0.000046, "InputBytes" -> 16, "OutputBytes" -> 16, 
  "InputTerms" -> 1, "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 73, "Method" -> "WholeSimplify", 
  "Seconds" -> 0.000438, "InputBytes" -> 16, "OutputBytes" -> 16, 
  "InputTerms" -> 1, "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 73, 
  "Method" -> "TogetherThenSimplify", "Seconds" -> 0.000208, 
  "InputBytes" -> 16, "OutputBytes" -> 16, "InputTerms" -> 1, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 73, 
  "Method" -> "SimplifyThenTogether", "Seconds" -> 0.00021, 
  "InputBytes" -> 16, "OutputBytes" -> 16, "InputTerms" -> 1, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 73, "Method" -> "HistoricalCollect", 
  "Seconds" -> 0.000192, "InputBytes" -> 16, "OutputBytes" -> 16, 
  "InputTerms" -> 1, "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>, <|"Position" -> 73, 
  "Method" -> "TogetherThenHistoricalCollect", "Seconds" -> 0.000179, 
  "InputBytes" -> 16, "OutputBytes" -> 16, "InputTerms" -> 1, 
  "OutputTerms" -> 1, "RemainingFractionVariables" -> {}, 
  "ExactData" -> True, "ExactEquality" -> True, "TimedOut" -> False, 
  "Failed" -> False|>}
