{<|"FactorID" -> 23, "Factor" -> facetX, "DenominatorIncidence" -> 5703, 
  "TotalExponent" -> 10111, "MaximumExponent" -> 4|>, 
 <|"FactorID" -> 1, "Factor" -> -1 + facetX + facetY, 
  "DenominatorIncidence" -> 4437, "TotalExponent" -> 7314, 
  "MaximumExponent" -> 6|>, <|"FactorID" -> 12, "Factor" -> -1 + facetY, 
  "DenominatorIncidence" -> 4313, "TotalExponent" -> 8726, 
  "MaximumExponent" -> 5|>, <|"FactorID" -> 18, "Factor" -> facetY, 
  "DenominatorIncidence" -> 2297, "TotalExponent" -> 2840, 
  "MaximumExponent" -> 4|>, <|"FactorID" -> 28, "Factor" -> facetX + facetY, 
  "DenominatorIncidence" -> 1711, "TotalExponent" -> 2955, 
  "MaximumExponent" -> 6|>, <|"FactorID" -> 6, "Factor" -> -1 + facetX, 
  "DenominatorIncidence" -> 1216, "TotalExponent" -> 1875, 
  "MaximumExponent" -> 4|>, <|"FactorID" -> 11, 
  "Factor" -> 1 + facetX - facetY, "DenominatorIncidence" -> 527, 
  "TotalExponent" -> 744, "MaximumExponent" -> 3|>, 
 <|"FactorID" -> 27, "Factor" -> (3 + 5*Global`Epsilon + facetX + 
     Global`Epsilon*facetX - 3*facetY - 5*Global`Epsilon*facetY)/
    (1 + Global`Epsilon), "DenominatorIncidence" -> 359, 
  "TotalExponent" -> 359, "MaximumExponent" -> 1|>, 
 <|"FactorID" -> 19, "Factor" -> 1 + 2*facetX + facetX^2 - 2*facetY + 
    2*facetX*facetY + facetY^2, "DenominatorIncidence" -> 258, 
  "TotalExponent" -> 396, "MaximumExponent" -> 3|>, 
 <|"FactorID" -> 17, "Factor" -> 1 + facetX + facetY, 
  "DenominatorIncidence" -> 251, "TotalExponent" -> 253, 
  "MaximumExponent" -> 2|>, <|"FactorID" -> 9, 
  "Factor" -> 1 - 2*facetX + facetX^2 - 2*facetY - 2*facetX*facetY + 
    facetY^2, "DenominatorIncidence" -> 250, "TotalExponent" -> 394, 
  "MaximumExponent" -> 3|>, <|"FactorID" -> 30, 
  "Factor" -> -1 + facetX - facetY, "DenominatorIncidence" -> 245, 
  "TotalExponent" -> 247, "MaximumExponent" -> 2|>, 
 <|"FactorID" -> 5, "Factor" -> 1 - 2*facetX + facetX^2 + 2*facetY + 
    2*facetX*facetY + facetY^2, "DenominatorIncidence" -> 121, 
  "TotalExponent" -> 193, "MaximumExponent" -> 3|>, 
 <|"FactorID" -> 15, "Factor" -> facetX + facetY - facetY^2, 
  "DenominatorIncidence" -> 96, "TotalExponent" -> 146, 
  "MaximumExponent" -> 3|>, <|"FactorID" -> 8, 
  "Factor" -> facetX^2 - facetY + 2*facetX*facetY + facetY^2, 
  "DenominatorIncidence" -> 77, "TotalExponent" -> 107, 
  "MaximumExponent" -> 2|>, <|"FactorID" -> 22, 
  "Factor" -> 1 - facetY + facetX*facetY, "DenominatorIncidence" -> 64, 
  "TotalExponent" -> 76, "MaximumExponent" -> 2|>, 
 <|"FactorID" -> 13, "Factor" -> 1 - 2*facetX + facetX^2 - facetY, 
  "DenominatorIncidence" -> 64, "TotalExponent" -> 87, 
  "MaximumExponent" -> 2|>, <|"FactorID" -> 16, 
  "Factor" -> (-3 - 3*Global`Epsilon + 3*facetX + 5*Global`Epsilon*facetX + 
     3*facetY + 5*Global`Epsilon*facetY)/(3 + 5*Global`Epsilon), 
  "DenominatorIncidence" -> 57, "TotalExponent" -> 57, 
  "MaximumExponent" -> 1|>, <|"FactorID" -> 7, 
  "Factor" -> (-3 - 5*Global`Epsilon + 3*facetX + 5*Global`Epsilon*facetX + 
     3*facetY + 3*Global`Epsilon*facetY)/(3 + 5*Global`Epsilon), 
  "DenominatorIncidence" -> 57, "TotalExponent" -> 57, 
  "MaximumExponent" -> 1|>, <|"FactorID" -> 3, 
  "Factor" -> facetX - facetY + facetX*facetY + facetY^2, 
  "DenominatorIncidence" -> 35, "TotalExponent" -> 35, 
  "MaximumExponent" -> 1|>, <|"FactorID" -> 26, "Factor" -> 1 + facetY, 
  "DenominatorIncidence" -> 33, "TotalExponent" -> 35, 
  "MaximumExponent" -> 2|>, <|"FactorID" -> 29, 
  "Factor" -> -1 + facetX + facetY + facetX*facetY, 
  "DenominatorIncidence" -> 29, "TotalExponent" -> 29, 
  "MaximumExponent" -> 1|>, <|"FactorID" -> 24, 
  "Factor" -> 1 - 2*facetY + facetX*facetY + facetY^2, 
  "DenominatorIncidence" -> 21, "TotalExponent" -> 29, 
  "MaximumExponent" -> 2|>, <|"FactorID" -> 4, 
  "Factor" -> -facetX + facetX^2 + 2*facetX*facetY + facetY^2, 
  "DenominatorIncidence" -> 14, "TotalExponent" -> 14, 
  "MaximumExponent" -> 1|>, <|"FactorID" -> 14, 
  "Factor" -> 1 - 2*facetX + facetX^2 + facetX*facetY, 
  "DenominatorIncidence" -> 13, "TotalExponent" -> 13, 
  "MaximumExponent" -> 1|>, <|"FactorID" -> 25, 
  "Factor" -> -1 + facetX + 2*facetY - facetY^2, "DenominatorIncidence" -> 9, 
  "TotalExponent" -> 9, "MaximumExponent" -> 1|>, 
 <|"FactorID" -> 20, "Factor" -> (-1 - 2*Global`Epsilon - facetX - 
     2*Global`Epsilon*facetX - facetY - 2*Global`Epsilon*facetY + 
     facetX*facetY + Global`Epsilon*facetX*facetY)/(1 + Global`Epsilon), 
  "DenominatorIncidence" -> 8, "TotalExponent" -> 8, 
  "MaximumExponent" -> 1|>, <|"FactorID" -> 21, 
  "Factor" -> (-facetX - Global`Epsilon*facetX - facetY - 
     2*Global`Epsilon*facetY + facetX*facetY + 2*Global`Epsilon*facetX*
      facetY - facetY^2 - 2*Global`Epsilon*facetY^2)/(1 + 2*Global`Epsilon), 
  "DenominatorIncidence" -> 7, "TotalExponent" -> 7, 
  "MaximumExponent" -> 1|>, <|"FactorID" -> 10, "Factor" -> facetX - facetY, 
  "DenominatorIncidence" -> 3, "TotalExponent" -> 4, 
  "MaximumExponent" -> 2|>, <|"FactorID" -> 2, "Factor" -> 1 + facetX, 
  "DenominatorIncidence" -> 3, "TotalExponent" -> 4, "MaximumExponent" -> 2|>}
