(* Bare lower-order results are complete Laurent distributions, never finite
   renormalized hard coefficients. Flavor covariance is declared by the card
   and the electromagnetic charge factor is checked in every scalar entry. *)
BeginPackage["FeynFacet`"];
ResolveBarePartonicSource::usage="ResolveBarePartonicSource[catalog,order,species,flavorClasses,through] resolves a lower-order source. An optional sixth argument selects its full declared source channel, including recoil. Explicit minimum channel orders determine exact zeros. Massless QCD uses declared flavor covariance; current single-quark-line relabeling requires an exactly factored external squared charge and rejects hidden charge sums.";
ConstructPartonicCounterterm::usage="ConstructPartonicCounterterm[countertermCard] constructs the UV and collinear correction through relative order two from automatically generated bare lower-order amplitudes and physical PDF/FF leg declarations. BareOperatorSchemes names the schemes of the generated sources. A finite operator-scheme conversion is a separate step.";

ConstructSubtractedPartonicSourceCatalog::usage="ConstructSubtractedPartonicSourceCatalog[countertermCard] applies UV and raw-scheme collinear subtraction to automatically regenerated lower-order bare sources, verifies exact pole cancellation, and retains finite LO/NLO coefficients for a later operator scheme change.";
ResolveRenormalizedPartonicSource::usage="ResolveRenormalizedPartonicSource[catalog,order,species,flavorClasses,through] resolves a raw-subtracted lower-order coefficient with the same checked physical-channel and flavor covariance as the bare resolver. An optional sixth argument selects the full declared source channel. Already finite-scheme-converted sources are rejected.";
ConstructFiniteFactorizationCounterterm::usage="ConstructFiniteFactorizationCounterterm[card,catalog] constructs the finite change from the declared bare operator scheme to the target scheme through relative order two, using a verified subtracted lower-order catalog.";
PlanCountertermContribution::usage="PlanCountertermContribution[card] resolves the declared counterterm operator products and their exact source epsilon requirements before source generation.";
ConstructCountertermContribution::usage="ConstructCountertermContribution[compiledCard] evaluates one explicit source-channel counterterm card, automatically generating bare sources and performing the checked raw subtraction required before a finite scheme conversion.";
Begin["`Private`"];

bareSourceFail[tag_,data_:<||>]:=Throw[Failure[tag,data],"BarePartonicSources"];
bareFlavorPattern[species_List]:=Module[{flavors=DeleteDuplicates[Last/@Select[species,#=!="g"&]],index},
 index=AssociationThread[flavors,Range[Length[flavors]]];
 (If[#==="g","g",{First[#],index[Last[#]]}]&/@species)
];
bareChannelSpecies[channel_Association]:=If[KeyExistsQ[channel,"Observed"],
  Append[channel["Incoming"],channel["Observed"]],channel["Incoming"]];
bareSourceChannelCandidates[channels_Association,species_List]:=Module[{names,exact,signature},
 names=Select[Keys[channels],bareFlavorPattern[bareChannelSpecies[channels[#]]]===bareFlavorPattern[species]&];
 exact=Select[names,bareChannelSpecies[channels[#]]===species&];
 If[exact=!={},Return[exact]];
 signature[name_]:=With[{channel=channels[name]},
  {KeyExistsQ[channel,"Observed"],KeyExistsQ[channel,"Recoil"],
   bareFlavorPattern[Join[bareChannelSpecies[channel],If[KeyExistsQ[channel,"Recoil"],{channel["Recoil"]},{}]]]}];
 First/@GatherBy[names,signature]
];
resolvePartonicSource[catalog_Association,order_Integer,species_List,
 classMap_Association,through_Integer,stage_String,selection_:Automatic]:=Catch[Module[
 {names,name,pattern,channel,source,originalSpecies,sourceFlavors,targetFlavors,sourceClass,
  targetClass,sourceCharge,targetCharge,quotient,coefficients,transform,metadata,classes,relabel,physical},
 If[!MemberQ[{"FeynFacet-BarePartonicSourceCatalog","FeynFacet-SubtractedPartonicSourceCatalog"},Lookup[catalog,"Format",None]]||
   !MemberQ[{0,1},order]||!AllTrue[species,collinearKernelSpeciesQ],
   bareSourceFail["LowerOrderBareSourceCatalogRequired"]];
 pattern=bareFlavorPattern[species];
 names=If[StringQ[selection],{selection},bareSourceChannelCandidates[catalog["Channels"],species]];
 If[names==={}&&TrueQ[Lookup[catalog,"CompleteLowerOrderSourceCatalog",False]],Return[0]];
 If[Length[names]=!=1||!KeyExistsQ[catalog["Channels"],First[names]],
  bareSourceFail["ExplicitSourceChannelRequired",<|"Species"->species,"Candidates"->names|>]];
 If[bareFlavorPattern[bareChannelSpecies[catalog["Channels"][First[names]]]]=!=pattern,
  bareSourceFail["SourceChannelFlavorPatternMismatch"]];
 name=First[names];channel=catalog["Channels"][name];
 If[order<catalog["MinimumChannelOrders"][name],Return[0]];
 source=Lookup[Lookup[catalog["Sources"],order,<||>],name,Missing[]];
 If[!AssociationQ[source]||Lookup[source,"RenormalizationStage",None]=!=stage,
  bareSourceFail["DeclaredNonzeroBareSourceMissing",<|"Order"->order,"Channel"->name|>]];
 If[stage==="Renormalized"&&TrueQ[Lookup[source,"FiniteSchemeConversionApplied",False]],
  bareSourceFail["AlreadyConvertedFiniteSchemeSourceRejected"]];
 If[FeynFacet`RequirePartonicEpsilonRange[source,{source["LaurentLowerBound"],through}]=!=True,
  bareSourceFail["BareSourceEpsilonOrdersInsufficient",<|"Order"->order,"Channel"->name,"ThroughOrder"->through|>]];
 originalSpecies=bareChannelSpecies[channel];
 sourceFlavors=DeleteDuplicates[Last/@Select[originalSpecies,#=!="g"&]];
 targetFlavors=DeleteDuplicates[Last/@Select[species,#=!="g"&]];
 If[Lookup[catalog,"FlavorCovariance",None]==="MasslessQCD",
  If[Length[sourceFlavors]=!=Length[targetFlavors],bareSourceFail["MasslessFlavorRelabelingRequired"]];
  relabel=Thread[sourceFlavors->targetFlavors];
  physical=Join[channel,<|"Incoming"->Take[species,Length[channel["Incoming"]]]|>,
   If[KeyExistsQ[channel,"Observed"],<|"Observed"->Last[species]|>,<||>],
   If[KeyExistsQ[channel,"Recoil"],<|"Recoil"->(channel["Recoil"]/.relabel)|>,<||>]];
  Return[FeynFacet`CreatePartonicResult[source["Coefficients"],
   Join[KeyDrop[source,{"Coefficients","EpsilonRange","ProcessDefinition"}],
    <|"PhysicalChannel"->physical,"SourceFlavorChannel"->channel,"SourceChannel"->name,
      "ResolvedFlavorSpecies"->species,"FlavorRelabeling"-><|"Convention"->"MasslessQCD",
       "FlavorRules"->relabel,"FullPhysicalChannelRetained"->True|>|>]]]];
 If[Length[sourceFlavors]=!=1||Length[targetFlavors]=!=1,
  bareSourceFail["SingleMasslessQuarkLineRequired"]];
 classes=catalog["FlavorClasses"];
 sourceClass=Select[Keys[classes],MemberQ[classes[#]["Members"],First[sourceFlavors]]&];
 targetClass=Lookup[classMap,First[targetFlavors],Missing[]];
 If[Length[sourceClass]=!=1||!KeyExistsQ[classes,targetClass],
  bareSourceFail["SourceAndTargetFlavorChargeClassesRequired"]];
 sourceCharge=classes[First[sourceClass]]["Charge"];targetCharge=classes[targetClass]["Charge"];
 transform[value_]:=Module[{q=Cancel[Together[value/sourceCharge^2]]},
   If[!FreeQ[q,Alternatives@@catalog["ChargeSymbols"]],
    bareSourceFail["SingleExternalChargeFactorNotEstablished",<|"Channel"->name|>]];
   targetCharge^2 q];
 coefficients=Map[partonicMap[transform,#]&,source["Coefficients"]];
 metadata=Join[KeyDrop[source,{"Coefficients","EpsilonRange","ProcessDefinition"}],
  <|"PhysicalChannel"->If[KeyExistsQ[channel,"Observed"],
     <|"Incoming"->Most[species],"Observed"->Last[species]|>,<|"Incoming"->species|>],
    "SourceFlavorChannel"->channel,"ResolvedFlavorSpecies"->species,
    "FlavorRelabeling"-><|"SourceFlavor"->First[sourceFlavors],"TargetFlavor"->First[targetFlavors],
      "SourceCharge"->sourceCharge,"TargetCharge"->targetCharge,
      "ChargeIndependentRemainderVerified"->True|>|>];
 FeynFacet`CreatePartonicResult[coefficients,metadata]
],"BarePartonicSources"];

ResolveBarePartonicSource[catalog_Association,order_Integer,species_List,classes_Association,through_Integer]:=
 resolvePartonicSource[catalog,order,species,classes,through,"Bare"];
ResolveRenormalizedPartonicSource[catalog_Association,order_Integer,species_List,classes_Association,through_Integer]:=
 resolvePartonicSource[catalog,order,species,classes,through,"Renormalized"];

ResolveBarePartonicSource[catalog_Association,order_Integer,species_List,classes_Association,through_Integer,channel_String]:=
 resolvePartonicSource[catalog,order,species,classes,through,"Bare",channel];
ResolveRenormalizedPartonicSource[catalog_Association,order_Integer,species_List,classes_Association,through_Integer,channel_String]:=
 resolvePartonicSource[catalog,order,species,classes,through,"Renormalized",channel];

partonicBindSourceChannels[plan_Association,card_Association,targetName_:Automatic]:=Module[{rows={},names,pattern},
 Do[
  pattern=bareFlavorPattern[row["SourceSpecies"]];
  names=If[StringQ[Lookup[row,"SourceChannel",None]],{row["SourceChannel"]},
   If[StringQ[targetName]&&row["SourceOrder"]===plan["PerturbativeOrder"]&&row["Kernels"]==={},
    {targetName},bareSourceChannelCandidates[card["Channels"],row["SourceSpecies"]]]];
  If[names==={}&&!TrueQ[Lookup[card,"CompleteLowerOrderSourceCatalog",False]],
   bareSourceFail["DeclaredSourceFlavorChannelRequired",<|"Species"->row["SourceSpecies"]|>]];
  rows=Join[rows,Join[row,<|"SourceChannel"->#|>]&/@Select[names,
    row["SourceOrder"]>=card["MinimumChannelOrders"][#]&]],
 {row,plan["Terms"]}];
 Join[plan,<|"Terms"->rows|>]
];


(* A concrete card selects terms of the general flavor-correlated expansion.
   The factors and their multiplicities remain those of the mathematical plan. *)
partonicCountertermCardPlan[plan_Association,card_Association]:=Module[
 {sourceOrder,pattern,legNames,termOrders,selected={},desiredStage,ct,mode,legs,defaultLegs,request,
  productOrders,entry,allowed,role,expected,parameters,subplan,rows,weight,position,spec,leg,spin},
 If[!KeyExistsQ[card,"SourceOrder"],Return[partonicBindSourceChannels[plan,card]]];
 sourceOrder=Switch[card["SourceOrder"],"LO",0,"NLO",1,_,bareSourceFail["LowerCountertermSourceOrderRequired"]];
 pattern=bareFlavorPattern[bareChannelSpecies[card["Channels"][card["SourceChannel"]]]];
 legNames=Keys[card["Assembly"]["FactorizationLegs"]];
 desiredStage=Lookup[card,"SourceRenormalizationStage","Bare"];ct=card["Counterterms"];
 If[Lookup[plan,"SourceRenormalizationStage","Bare"]=!=desiredStage,
  bareSourceFail["CountertermCardAndPlanSourceStagesDiffer"]];
 mode=If[desiredStage==="Bare","Raw","Finite"];
 allowed={"Distribution","PerturbativeOrder","Operation","FlavorMultiplicity","PoleNormalization",
   "ScaleLog","OperatorScheme","OperatorRedefinition","KernelParameters","Spin","Variable"};
 termOrders[row_]:=Module[{powers,uv},
  powers=Association@Table[legNames[[kernel["Leg"]]]->kernel["PerturbativeOrder"],{kernel,row["Kernels"]}];
  uv=plan["PerturbativeOrder"]-row["SourceOrder"]-Total[Values[powers]];
  If[uv>0,AssociateTo[powers,"Coupling"->uv]];KeySort[powers]];
 Do[
  defaultLegs=partonicCardFactorizationLegs[card,mode];legs=defaultLegs;
  weight=Lookup[card,"FlavorMultiplicity",1];
  KeyValueMap[Function[{name,definition},
   spec=definition;
   If[!SubsetQ[allowed,Keys[spec]],bareSourceFail["UnsupportedCountertermInsertionFields",
    <|"Fields"->Complement[Keys[spec],allowed]|>]];
   expected=If[mode==="Raw","CollinearSubtraction","FiniteSchemeChange"];
   If[spec["Operation"]=!=expected,bareSourceFail["CountertermOperationDoesNotMatchSourceStage"]];
   If[name==="Coupling",
    If[spec["Distribution"]=!="CouplingCounterterm"||mode=!="Raw"||
      !SubsetQ[{"Distribution","PerturbativeOrder","Operation","FlavorMultiplicity"},Keys[spec]],
     bareSourceFail["UnsupportedCouplingCountertermInsertion"]],
    position=FirstPosition[legNames,name,Missing[]];
    If[MissingQ[position],bareSourceFail["DeclaredFactorizationLegRequired"]];
    position=First[position];leg=legs[[position]];role=leg["Role"];
    If[spec["Distribution"]=!=If[role==="PDF","PDFCounterterm","FFCounterterm"],
     bareSourceFail["CountertermDistributionRoleMismatch"]];
    If[Lookup[spec,"Spin",leg["Spin"]]=!=leg["Spin"]||
      Lookup[spec,"Variable",leg["Variable"]]=!=leg["Variable"]||
      Lookup[spec,"KernelParameters",ct["KernelParameters"]]=!=ct["KernelParameters"],
     bareSourceFail["CountertermOperatorMustPreservePhysicalSpinCoordinatesAndQCDParameters"]];
    If[Lookup[spec,"PoleNormalization",ct["PoleNormalization"]]=!=ct["PoleNormalization"],
     bareSourceFail["CountertermPoleNormalizationMustMatchDeclaredBareCoupling"]];
    If[mode==="Raw"&&Lookup[spec,"OperatorScheme",leg["OperatorScheme"]]=!=leg["OperatorScheme"],
     bareSourceFail["CountertermRawOperatorMustMatchGeneratedSourceScheme"]];
    If[(mode==="Raw"&&KeyExistsQ[spec,"OperatorRedefinition"])||
       (mode==="Finite"&&KeyExistsQ[spec,"OperatorScheme"]),
     bareSourceFail["RawAndFiniteOperatorSchemeFieldsMustBeSeparate"]];
    legs[[position]]=Join[leg,KeyTake[spec,{"PoleNormalization","ScaleLog","OperatorScheme","OperatorRedefinition"}]]];
   weight*=Lookup[spec,"FlavorMultiplicity",1]
  ],product];
  If[!FreeQ[weight,plan["DimensionalRegulator"]|_Real|_Failure|_Missing|Indeterminate|_DirectedInfinity]||
    !FreeQ[weight,Alternatives@@Lookup[legs,"Variable"]],
   bareSourceFail["ExactExternalEpsilonIndependentCountertermMultiplicityRequired"]];
  request=<|"PerturbativeOrder"->plan["PerturbativeOrder"],"ThroughOrder"->plan["ThroughOrder"],
    "DimensionalRegulator"->plan["DimensionalRegulator"],"PerturbativeParameter"->plan["PerturbativeParameter"],
    "BornCouplingPower"->card["BornCouplingPower"],"Legs"->legs,
     "FlavorClasses"->card["FlavorClasses"],"KernelParameters"->ct["KernelParameters"],
    "CouplingNormalization"->ct["CouplingNormalization"]|>;
  If[mode==="Raw"&&!MemberQ[card["Include"],"UV"],AssociateTo[request,"CouplingRenormalization"-><|1->0,2->0|>]];
  (* The supplied plan already contains every default operator product.
     Rebuild only when an insertion changes an actual kernel or scale. *)
  subplan=If[legs===defaultLegs,plan,
   If[mode==="Raw",FeynFacet`PlanCollinearRenormalization[plan["TargetSpecies"],request],
    FeynFacet`PlanFiniteFactorizationSchemeChange[plan["TargetSpecies"],request]]];
  If[!AssociationQ[subplan],bareSourceFail["CountertermInsertionPlanFailed",<|"Cause"->subplan|>]];
  productOrders=KeySort[Map[#["PerturbativeOrder"]&,product]];
  rows=Select[subplan["Terms"],#["SourceOrder"]===sourceOrder&&
   MemberQ[bareSourceChannelCandidates[card["Channels"],#["SourceSpecies"]],card["SourceChannel"]]&&
   termOrders[#]===productOrders&];
  selected=Join[selected,Join[#,<|"Factor"->weight #["Factor"],"SourceChannel"->card["SourceChannel"]|>]&/@rows],
 {product,card["OperatorInsertions"]}];
 If[selected==={},bareSourceFail["CountertermCardHasNoMatchingPlanTerms"]];
 Join[plan,<|"Terms"->selected,"SourceContributionCard"->KeyTake[card,
   {"CardName","SourceOrder","SourceChannel","SourceRenormalizationStage","OperatorInsertions"}]|>]
];


PlanCountertermContribution[card_Association]:=Catch[Module[
 {stage,mode,ct,legs,order,request,plan,target},
 If[KeyExistsQ[card,"TargetCards"],
  plan=Map[FeynFacet`PlanCountertermContribution,card["TargetCards"]];
  If[!AllTrue[plan,AssociationQ],bareSourceFail["CountertermChannelPlansRequired",<|"Cause"->plan|>]];
  Return[<|"SourceChannel"->card["SourceChannel"],"ChannelPlans"->plan|>]];
 If[card["Order"]==="NLO",Return[projectPlanNLOCountertermCards[<|card["CardName"]->card|>]]];
 stage=Lookup[card,"SourceRenormalizationStage","Bare"];
 mode=If[stage==="Bare","Raw","Finite"];ct=card["Counterterms"];
 legs=partonicCardFactorizationLegs[card,mode];order=2;
 target=bareChannelSpecies[card["Channels"][card["Channel"]]];
 request=<|"PerturbativeOrder"->order,"ThroughOrder"->Last[card["EpsilonRange"]],
  "DimensionalRegulator"->Global`Epsilon,"PerturbativeParameter"->ct["Coupling"]/(2Pi),
  "BornCouplingPower"->card["BornCouplingPower"],"Legs"->legs,"FlavorClasses"->card["FlavorClasses"],
  "KernelParameters"->ct["KernelParameters"],"CouplingNormalization"->ct["CouplingNormalization"]|>;
 If[mode==="Raw"&&!MemberQ[card["Include"],"UV"],AssociateTo[request,"CouplingRenormalization"-><|1->0,2->0|>]];
 plan=If[mode==="Raw",FeynFacet`PlanCollinearRenormalization[target,request],
   FeynFacet`PlanFiniteFactorizationSchemeChange[target,request]];
 If[!AssociationQ[plan],bareSourceFail["CountertermContributionPlanFailed",<|"Cause"->plan|>]];
 plan=Join[plan,<|"Terms"->Select[plan["Terms"],#["SourceOrder"]<order&]|>];
 partonicCountertermCardPlan[plan,card]
],"BarePartonicSources"];

ConstructCountertermContribution[card_Association]:=Catch[Module[
 {catalog,value,stage,range,lower,zero,coefficients,omitted},
 If[KeyExistsQ[card,"TargetCards"],
  value=Map[FeynFacet`ConstructCountertermContribution,card["TargetCards"]];
  If[!AllTrue[value,AssociationQ],bareSourceFail["CountertermChannelResultsRequired",<|"Cause"->value|>]];
  Return[<|"Format"->"FeynFacet-PartonicChannelResults","FormatVersion"->1,"Project"->card["Project"],
   "Order"->card["Order"],"SourceOrder"->card["SourceOrder"],"SourceChannel"->card["SourceChannel"],
   "Contribution"->"Counterterm","Results"->value|>]];
 If[!ContainsAll[Keys[card],{"SourceOrder","SourceChannel","OperatorInsertions"}],
  bareSourceFail["ConcreteCountertermCardRequired"]];
 stage=Lookup[card,"SourceRenormalizationStage","Bare"];
 value=Which[
  Lookup[card,"Order",None]==="NLO",FeynFacet`ConstructNLOCountertermContribution[card],
  stage==="Bare",ConstructPartonicCounterterm[card],
  stage==="Renormalized",
   catalog=ConstructSubtractedPartonicSourceCatalog[card];
   If[!AssociationQ[catalog],bareSourceFail["AutomaticSubtractedSourcesFailed",<|"Cause"->catalog|>]];
   ConstructFiniteFactorizationCounterterm[card,catalog],
  True,bareSourceFail["ExplicitCountertermSourceStageRequired"]];
 If[!AssociationQ[value],bareSourceFail["AutomaticCountertermContributionFailed",<|"Cause"->value|>]];
 range=card["EpsilonRange"];lower=value["LaurentLowerBound"];
 If[Last[value["EpsilonRange"]]<Last[range],bareSourceFail["CountertermUpperEpsilonOrdersInsufficient"]];
 omitted=KeySelect[value["Coefficients"],#<First[range]&];
 If[!AllTrue[Values[omitted],partonicZeroTreeQ],bareSourceFail["CountertermCardOmitsNonzeroPoles"]];
 zero=partonicDistributionZero[partonicDistributionDepth[value["DistributionBasis"]]];
 coefficients=Association@Table[n->If[KeyExistsQ[value["Coefficients"],n],value["Coefficients"][n],
   If[n<lower,zero,bareSourceFail["UncomputedCountertermEpsilonCoefficient",<|"Order"->n|>]]],
  {n,First[range],Last[range]}];
 value=FeynFacet`CreatePartonicResult[coefficients,Join[
   KeyDrop[value,{"Coefficients","EpsilonRange","LaurentLowerBound"}],
   <|"ComputedLaurentLowerBound"->lower,"KnownZeroOrdersBelowComputedBound"->Range[First[range],lower-1]|>]];
 If[!AssociationQ[value],bareSourceFail["CountertermDeclaredRangeStorageFailed"]];
 Join[value,If[AssociationQ[catalog],<|"GeneratedSources"->catalog["GeneratedSources"],
   "SourceGenerationSeconds"->catalog["StageSeconds"]|>,<||>],
  <|"Contribution"->"Counterterm","ContributionCard"->KeyTake[card,
   {"CardName","SourceOrder","SourceChannel","SourceRenormalizationStage","OperatorInsertions"}]|>]
],"BarePartonicSources"];

(* Shared physical-leg construction for pole subtraction and finite changes. *)
partonicCardFactorizationLegs[card_,mode_]:=Module[{ct=card["Counterterms"],raw=card["BareOperatorSchemes"],role,spin,source,target,redefinition},
 KeyValueMap[Function[{name,definition},
  role=definition["Role"];
  spin=If[role==="PDF",card["Polarization"]["Incoming"][[Lookup[definition,"Index",1]]],card["Polarization"]["Observed"]];
  source=raw[name];target=ct["Schemes"][name];
  redefinition=Which[source===target,"MSbar",
   source==="Larin"&&(target==="HelicityMSbar"||
      (AssociationQ[target]&&Lookup[target,"DefaultScheme","MSbar"]==="HelicityMSbar")),target,
   source==="MSbar"&&AssociationQ[target]&&Lookup[target,"DefaultScheme","MSbar"]==="MSbar",target,
   True,If[mode==="Finite",bareSourceFail["ExplicitFiniteOperatorSchemeRelationRequired",
     <|"SourceScheme"->source,"TargetScheme"->target|>],"MSbar"]];
  Join[<|"Name"->name,"Role"->role,"Spin"->spin,"Variable"->definition["Variable"],
   "ScaleLog"->Log[ct["FactorizationScalesSquared"][name]/ct["RenormalizationScaleSquared"]],
   "PoleNormalization"->Lookup[ct,"PoleNormalization",1],
   "ConvolutionRequest"->Join[KeyTake[card["Assembly"],{"Scale","Variables","Assumptions"}],
     <|"Convolution"->card["Assembly"]["CollinearConvolution"],"Leg"->name|>,
     If[KeyExistsQ[Lookup[card["Assembly"],"CollinearMaps",<||>],name],
      <|"CollinearMap"->card["Assembly"]["CollinearMaps"][name]|>,<||>]]|>,
   If[mode==="Finite",<|"OperatorScheme"->source,"OperatorRedefinition"->redefinition|>,<|"OperatorScheme"->source|>]]
 ],card["Assembly"]["FactorizationLegs"]]
];

ConstructSubtractedPartonicSourceCatalog[card_Association]:=Catch[Module[
 {catalog,legs,ct,e,a,source,request,plan,metadata,value,coefficients,poles,rows=<||>,
  orderRows,name,order,conditions,axes,output,requirements={},orderName,sourceDefinitions},
 legs=partonicCardFactorizationLegs[card,"Raw"];ct=card["Counterterms"];e=Global`Epsilon;a=ct["Coupling"]/(2Pi);
 sourceDefinitions=card["BareSourceContributions"];
 Do[
  order=Switch[orderName,"LO",0,"NLO",1,_,bareSourceFail["LowerOrderBareSourceOnly"]];
  request=<|"PerturbativeOrder"->order,"ThroughOrder"->0,"DimensionalRegulator"->e,
    "PerturbativeParameter"->a,"BornCouplingPower"->card["BornCouplingPower"],
    "Legs"->legs, "FlavorClasses"->card["FlavorClasses"],"KernelParameters"->ct["KernelParameters"],
    "CouplingNormalization"->ct["CouplingNormalization"]|>;
  Do[
   plan=FeynFacet`PlanCollinearRenormalization[bareChannelSpecies[card["Channels"][name]],request];
   If[!AssociationQ[plan],bareSourceFail["RawLowerOrderSubtractionPlanFailed",<|"Cause"->plan|>]];
   plan=partonicBindSourceChannels[plan,card,name];
   requirements=Join[requirements,plan["Terms"]],
  {name,If[KeyExistsQ[card,"SourceOrder"],
    If[orderName===card["SourceOrder"],{card["SourceChannel"]},{}],Keys[sourceDefinitions[orderName]]]}],
 {orderName,Take[{"LO","NLO"},Switch[card["Order"],"NLO",1,"NNLO",2,_,bareSourceFail["NLOOrNNLOConsumerRequired"]]]}];
 catalog=FeynFacet`GenerateBarePartonicSourceCatalog[card,requirements];
 If[!AssociationQ[catalog],bareSourceFail["GeneratedBareSourceCatalogRequired",<|"Cause"->catalog|>]];
 axes=Lookup[card["Assembly"]["DistributionBasis"],"Axes",{card["Assembly"]["DistributionBasis"]}];
 conditions=Lookup[card["Assembly"],"Assumptions",True]&&
  And@@Map[#[["Interval",1]]<#["Variable"]<#[["Interval",2]]&,axes];
 source[n_,species_,classes_,hi_,channel_]:=source[n,species,classes,hi,channel]=ResolveBarePartonicSource[catalog,n,species,classes,hi,channel];
 Do[orderRows=<||>;
  Do[
   metadata=Join[KeyDrop[catalog["Sources"][order][name],{"Coefficients","EpsilonRange","LaurentLowerBound","ProcessDefinition"}],
    <|"Contribution"->"Subtracted","RenormalizationStage"->"Renormalized",
     "OperatorSchemes"->card["BareOperatorSchemes"]|>];
   request=<|"PerturbativeOrder"->order,"ThroughOrder"->0,"DimensionalRegulator"->e,
    "PerturbativeParameter"->a,"BornCouplingPower"->card["BornCouplingPower"],
    "Legs"->legs, "FlavorClasses"->card["FlavorClasses"],"KernelParameters"->ct["KernelParameters"],
    "CouplingNormalization"->ct["CouplingNormalization"]|>;
   plan=FeynFacet`PlanCollinearRenormalization[bareChannelSpecies[card["Channels"][name]],request];
   If[!AssociationQ[plan],bareSourceFail["RawLowerOrderSubtractionPlanFailed",<|"Cause"->plan|>]];
   plan=partonicBindSourceChannels[plan,card,name];
   value=FeynFacet`ApplyPartonicRenormalization[plan,source,metadata];
   If[!AssociationQ[value],bareSourceFail["RawLowerOrderSubtractionFailed",<|"Channel"->name,"Cause"->value|>]];
   coefficients=FeynFacet`ExpandPositiveLogarithms[value["Coefficients"]/.Lookup[card,"ColorRules",{}],conditions];
   coefficients=Map[partonicMap[Function[scalar,Cancel[Together[scalar]]],#]&,coefficients];
   poles=KeySelect[coefficients,#<0&];
   If[!AllTrue[Values[poles],partonicZeroTreeQ],
    bareSourceFail["LowerOrderRawSchemePolesDidNotCancel",<|"Order"->order,"Channel"->name,"Poles"->poles|>]];
   output=FeynFacet`CreatePartonicResult[KeyTake[coefficients,{0}],Join[metadata,
    <|"RawSchemePoleCancellation"->True,"FiniteSchemeConversionApplied"->False|>]];
   AssociateTo[orderRows,name->output],
  {name,Keys[catalog["Sources"][order]]}];
  AssociateTo[rows,order->orderRows],
 {order,Keys[catalog["Sources"]]}];
 Join[catalog,<|"Format"->"FeynFacet-SubtractedPartonicSourceCatalog","Sources"->rows,
  "OperatorSchemes"->card["BareOperatorSchemes"],"RawSchemePoleCancellation"->True|>]
],"BarePartonicSources"];

ConstructFiniteFactorizationCounterterm[card_Association,catalog_Association]:=Catch[Module[
 {ct,legs,order,target,e,a,request,plan,source,metadata,result,rawSchemes},
 If[Lookup[catalog,"Format",None]=!="FeynFacet-SubtractedPartonicSourceCatalog"||
  !TrueQ[Lookup[catalog,"RawSchemePoleCancellation",False]]||
  catalog["Project"]=!=card["Project"]||catalog["Polarization"]=!=card["Polarization"]||
  catalog["OperatorSchemes"]=!=card["BareOperatorSchemes"],
  bareSourceFail["MatchingVerifiedSubtractedSourceCatalogRequired"]];
 order=Switch[card["Order"],"NLO",1,"NNLO",2,_,bareSourceFail["FiniteNLOOrNNLOSchemeChangeRequired"]];
 If[Last[card["EpsilonRange"]]=!=0,bareSourceFail["FiniteSchemeDefinesOnlyEpsilonZero"]];
 ct=card["Counterterms"];e=Global`Epsilon;a=ct["Coupling"]/(2Pi);
 legs=partonicCardFactorizationLegs[card,"Finite"];
 target=bareChannelSpecies[card["Channels"][card["Channel"]]];
 request=<|"PerturbativeOrder"->order,"ThroughOrder"->0,"DimensionalRegulator"->e,
  "PerturbativeParameter"->a,"BornCouplingPower"->card["BornCouplingPower"],
  "Legs"->legs, "FlavorClasses"->card["FlavorClasses"],"KernelParameters"->ct["KernelParameters"],
    "CouplingNormalization"->ct["CouplingNormalization"]|>;
 plan=FeynFacet`PlanFiniteFactorizationSchemeChange[target,request];
 If[!AssociationQ[plan],bareSourceFail["FiniteFactorizationSchemePlanFailed",<|"Cause"->plan|>]];
 plan=Join[plan,<|"Terms"->Select[plan["Terms"],#["SourceOrder"]<order&]|>];
 plan=partonicCountertermCardPlan[plan,card];
 source[n_,species_,classes_,hi_,channel_]:=source[n,species,classes,hi,channel]=ResolveRenormalizedPartonicSource[catalog,n,species,classes,hi,channel];
 metadata=Join[KeyTake[card["Assembly"],{"Scale","Variables","DensityConvention","DistributionBasis","CurrentNormalization"}],
  <|"DimensionalRegulator"->e,"DimensionalPrefactor"->ct["RenormalizationScaleSquared"]^(card["BornCouplingPower"]e),
   "Project"->card["Project"],"Order"->card["Order"],"Channel"->card["Channel"],
   "PhysicalChannel"->card["Channels"][card["Channel"]],"Polarization"->card["Polarization"],
   "StructureFunctions"->card["StructureFunctions"],"Coupling"->ct["Coupling"],
   "CouplingNormalization"->ct["CouplingNormalization"],
   "CouplingPower"->card["BornCouplingPower"]+order,"Contribution"->"FiniteFactorizationCounterterm",
   "RenormalizationStage"->"Counterterm","SourceOperatorSchemes"->card["BareOperatorSchemes"],
   "OperatorSchemes"->ct["Schemes"],"FiniteSchemeConversionApplied"->True|>];
 result=FeynFacet`ApplyPartonicRenormalization[plan,source,metadata];
 If[!AssociationQ[result],bareSourceFail["FiniteFactorizationSchemeApplicationFailed",<|"Cause"->result|>]];
 result=FeynFacet`CreatePartonicResult[
  Map[partonicMap[Function[value,Cancel[Together[value/.Lookup[card,"ColorRules",{}]]]],#]&,result["Coefficients"]],
  KeyDrop[result,{"Coefficients","EpsilonRange"}]];
 Join[result,<|"FiniteSchemePlan"->plan,"PositiveEpsilonSchemeContinuationDefined"->False|>]
],"BarePartonicSources"];

ConstructPartonicCounterterm[card_Association]:=Catch[Module[
 {catalog,order,through,e,a,legs,ct,schemes,target,request,plan,correction,metadata,
  source,answer,role,spin,rawScheme,legNames},
 order=Switch[Lookup[card,"Order",None],"NLO",1,"NNLO",2,_,bareSourceFail["NLOOrNNLOCountertermCardRequired"]];
 If[!ContainsAll[Keys[card],{"EpsilonRange","Assembly","Counterterms","BareOperatorSchemes","Include"}],
  bareSourceFail["ExplicitBareOperatorSchemesAndCountertermCardRequired"]];
 through=Last[card["EpsilonRange"]];e=Global`Epsilon;
 ct=card["Counterterms"];schemes=card["BareOperatorSchemes"];a=ct["Coupling"]/(2Pi);
 target=bareChannelSpecies[card["Channels"][card["Channel"]]];
 legNames=Keys[card["Assembly"]["FactorizationLegs"]];
 If[!ContainsAll[Keys[schemes],legNames],bareSourceFail["RawSchemeOfEveryFactorizationLegRequired"]];
 legs=partonicCardFactorizationLegs[card,"Raw"];
 If[Length[legs]=!=Length[target]||!ContainsAll[card["Include"],legNames],
  bareSourceFail["CompletePhysicalCollinearLegSelectionRequired"]];
 request=<|"PerturbativeOrder"->order,"ThroughOrder"->through,"DimensionalRegulator"->e,
  "PerturbativeParameter"->a,"BornCouplingPower"->card["BornCouplingPower"],
  "Legs"->legs, "FlavorClasses"->card["FlavorClasses"],"KernelParameters"->ct["KernelParameters"],
    "CouplingNormalization"->ct["CouplingNormalization"]|>;
 If[!MemberQ[card["Include"],"UV"],AssociateTo[request,"CouplingRenormalization"-><|1->0,2->0|>]];
 plan=FeynFacet`PlanCollinearRenormalization[target,request];
 If[!AssociationQ[plan],bareSourceFail["CountertermPlanFailed",<|"Cause"->plan|>]];
 correction=Join[plan,<|"Terms"->Select[plan["Terms"],#["SourceOrder"]<order&]|>];
 correction=partonicCountertermCardPlan[correction,card];
 catalog=FeynFacet`GenerateBarePartonicSourceCatalog[card,correction["Terms"]];
 If[!AssociationQ[catalog],bareSourceFail["AutomaticBareCountertermSourcesFailed",<|"Cause"->catalog|>]];
 source[n_,species_,classes_,hi_,channel_]:=source[n,species,classes,hi,channel]=
  ResolveBarePartonicSource[catalog,n,species,classes,hi,channel];
 metadata=Join[KeyTake[card["Assembly"],{"Scale","Variables","DensityConvention","DistributionBasis","CurrentNormalization"}],
  <|"DimensionalRegulator"->e,"DimensionalPrefactor"->ct["RenormalizationScaleSquared"]^(card["BornCouplingPower"]e),
   "Project"->card["Project"],"Order"->card["Order"],"Channel"->card["Channel"],
   "PhysicalChannel"->card["Channels"][card["Channel"]],"Polarization"->card["Polarization"],
   "StructureFunctions"->card["StructureFunctions"],"Coupling"->ct["Coupling"],
   "CouplingNormalization"->ct["CouplingNormalization"],
   "CouplingPower"->card["BornCouplingPower"]+order,"Contribution"->"Counterterm",
   "RenormalizationStage"->"Counterterm","BareOperatorSchemes"->schemes|>];
 answer=FeynFacet`ApplyPartonicRenormalization[correction,source,metadata];
 If[!AssociationQ[answer],bareSourceFail["PartonicCountertermApplicationFailed",<|"Cause"->answer|>]];
 Join[answer,<|"SourceOrderRequirements"->(KeyTake[#,{"SourceOrder","SourceChannel","SourceSpecies","RequiredSourceThroughOrder"}]&/@correction["Terms"]),
  "GeneratedSources"->catalog["GeneratedSources"],"SourceGenerationSeconds"->catalog["StageSeconds"],
  "SourceContributionDefinitions"->card["BareSourceContributions"],"FiniteSchemeConversionApplied"->False|>]
],"BarePartonicSources"];
End[];EndPackage[];
