(* Current processes use the same cards and physical result schema as scattering. *)
BeginPackage["FeynFacet`"];
RunNLOCurrentProject::usage="RunNLOCurrentProject[directory,mode] generates current Born dependencies and NLO real, virtual and PDF/FF counterterms, verifies pole cancellation, and saves an explicit common-format result.";
Begin["`Private`"];
RunNLOCurrentProject[directory_String,mode_String:"all"]:=Catch[Module[
 {location,project,channel,ctCard,needed,borns=<||>,declarations,dependencies,bornData,
  request,value,file,contributions=<||>,names,card,setup,density,combined,coefficients,range,
  conditions,color,poleCheck,final,meta,started=AbsoluteTime[],seconds,timings=<||>,check,write},
 If[!MemberQ[{"all","resume","assemble"},mode],projectFail["ProjectRunModeRequired"]];
 location=projectChannelLocation[directory];project=location["ProjectCard"];channel=location["Channel"];
 If[location["Order"]=!="NLO"||!KeyExistsQ[project,"Current"]||
  !MemberQ[{1,2},Length[project["Channels"][channel]["Incoming"]]],
  projectFail["OneOrTwoIncomingPartonCurrentProjectRequired"]];
 check[x_,tag_]:=projectCheck[x,tag];
 write[x_,suffix_]:=projectWrite[x,FileNameJoin[{directory,"Results",suffix}]];
 ctCard=check[ReadContributionCard[directory,"Counterterm"],"CurrentCountertermCardRequired"];
 needed={0,Last[ctCard["EpsilonRange"]]+1};declarations=ctCard["LowerOrderResults"];
 If[!AssociationQ[declarations]||declarations===<||>,projectFail["ExplicitLowerOrderResultsRequired"]];
 dependencies=projectLowerOrderDependencies[ctCard,"LO",Keys[declarations],needed];
 bornData=projectBornResults[project,dependencies,mode];
 borns=bornData["Results"];timings=Join[timings,bornData["StageSeconds"]];
 names=If[MemberQ[project["Orders"]["LO"],channel],{"Real","Virtual"},{"Real"}];
 Do[card=check[ReadContributionCard[directory,name],"CurrentContributionCardRequired"];
  setup=check[ReadProcessCard[card],"CurrentContributionSetupRequired"];
  request=Join[ProjectAssemblyRequest[card],ProjectResultIdentity[card,setup],
   <|"EpsilonRange"->card["EpsilonRange"]|>];
  file=FileNameJoin[{directory,"Results",name,"Result.wl"}];
  value=If[mode==="all",Failure["RegenerationRequested",<||>],ReadPartonicResult[file,
   Join[ProjectResultIdentity[card,setup],<|"EpsilonRange"->card["EpsilonRange"],
    "DistributionBasis"->project["Assembly"]["DistributionBasis"]|>]]];
  If[!AssociationQ[value],
   If[mode==="assemble",projectFail["CompleteMatchingCurrentContributionRequired",<|"Contribution"->name|>]];
   {seconds,value}=AbsoluteTiming[If[name==="Real",
     density=check[ConstructCurrentRealDensity[setup,request],"CurrentRealDensityFailed"];
     ConstructCurrentRealContribution[density,Join[request["EndpointExpansion"],<|"EpsilonRange"->card["EpsilonRange"]|>]],
     ConstructCurrentVirtualContribution[setup,request]]];
   check[value,"CurrentAnalyticContributionFailed"];projectWrite[value,file];AssociateTo[timings,name->seconds]];
  AssociateTo[contributions,name->value],{name,names}];
 request=Join[ProjectAssemblyRequest[ctCard,channel,"Real"],<|"EpsilonRange"->ctCard["EpsilonRange"],
  "Counterterms"->ctCard["Counterterms"],"Include"->ctCard["Include"],"LowerOrderResults"->declarations,
  "StructureFunctions"->project["StructureFunctions"]|>];
 {seconds,value}=AbsoluteTiming[ConstructCurrentCollinearCounterterm[borns,request]];
 check[value,"CurrentCollinearCountertermFailed"];write[value,"Counterterm/Result.wl"];
 AssociateTo[contributions,"Counterterm"->value];AssociateTo[timings,"Counterterm"->seconds];
 combined=check[CombinePartonicResults[contributions,<|"Contribution"->"Total"|>],"CurrentContributionCombinationFailed"];
 range=project["ResultEpsilonRanges"]["NLO"];
 If[FailureQ[RequirePartonicEpsilonRange[combined,range]],projectFail["CurrentOutputEpsilonRangeInsufficient"]];
 color=Lookup[project,"ColorRules",{}];
 conditions=Lookup[request,"Assumptions",True]&&
  And@@(#>0&/@Values[ctCard["Counterterms"]["FactorizationScalesSquared"]]);
 coefficients=Map[partonicMap[Function[value,
   FullSimplify[FunctionExpand[value/.color],Assumptions->conditions]],#]&,combined["Coefficients"]];
  combined=check[CreatePartonicResult[coefficients,Join[combined,<|"Assumptions"->conditions|>]],"SimplifiedCurrentResultRequired"];
  poleCheck=VerifyPartonicPoleCancellation[<|"Total"->combined|>];
  If[!AssociationQ[poleCheck]||poleCheck["Status"]=!="Passed",
   projectFail["CurrentPolesDoNotCancel",<|"Check"->poleCheck|>]];
  meta=<|"Contribution"->"Total","RequiredContributions"->Keys[contributions],
   "Assumptions"->conditions,"Schemes"->ctCard["Counterterms"]["Schemes"],"LowerOrderResults"->declarations|>;
  final=check[FinalizePartonicResults[<|"Total"->combined|>,poleCheck,<|
   "RequireAlgebraicIdentityProof"->True,"EpsilonRanges"-><|"Total"->range|>,"Metadata"->meta|>],"CurrentFinalResultFailed"];
  value=final["Total"];file=write[value,"Result.wl"];
 If[ReadPartonicResult[file]=!=value,projectFail["CurrentFinalResultReadBackFailed"]];
 meta=<|"Status"->"Completed","Project"->project["Project"],"Order"->"NLO","Channel"->channel,
  "Seconds"->AbsoluteTime[]-started,"StageSeconds"->timings,"ResultFile"->file,"EpsilonRange"->range,
  "StructureFunctions"->project["StructureFunctions"],"RequiredContributions"->Keys[contributions]|>;
 write[meta,"Validation/RunReport.wl"];meta
],"ProjectCards"];
End[];EndPackage[];
