(* Card-owned one-loop radiative densities. Scalar loop reduction precedes
   the measurement; endpoints and Hermitian completion remain explicit. *)
BeginPackage["FeynFacet`"];
PrepareMeasuredCurrentOneLoopContribution::usage="PrepareMeasuredCurrentOneLoopContribution[card,mode] generates a one-loop/tree current interference, reduces the virtual loop, and inserts the card's tuple measurement into physical three-particle phase space. It stores causal scalar integration representations and separate inclusive contacts in the contribution Work directory. This preparation does not write an accepted Results.wl.";
IntegrateMeasuredCurrentOneLoopInterior::usage="IntegrateMeasuredCurrentOneLoopInterior[card,mode] prepares the card-owned one-loop radiative density, verifies its energy endpoint integrability including original external causal factors, adds its conjugate on verified scalar branches, and integrates every noncontact tuple group through the requested Laurent range. It stores Hermitian GPL coefficients in Work/MeasuredOneLoopInterior.wl, before measurement-variable endpoint distributions. Compatible row records may be reused in resume mode.";
VerifyMeasuredCurrentOneLoopContactOrder::usage="VerifyMeasuredCurrentOneLoopContactOrder[card,mode] proves an ordinary-contact bound for every noncontact tuple density on its full two-variable integration domain and stores Work/MeasuredContactOrder.wl. It uses the original prescribed products and actual measurement maps; inclusive moments and contact coefficients remain separate. Matching proofs may be reused in resume mode.";
Begin["`Private`"];
measuredLoopInteriorReusableQ[row_,definition_,density_]:=Module[{range,labels,keys},
 If[!AssociationQ[row]||Lookup[row,"Format",None]=!="FeynFacet-OneLoopMeasuredInterior"||
   Lookup[row,"IntegrationDefinition",None]=!=definition||
   Lookup[Lookup[row,"InputCompanions",<||>],"Density",None]=!=density||
   !TrueQ[Lookup[row,"IntegralEvaluated",False]]||
   !TrueQ[Lookup[row,"ConjugateInterferenceAdded",False]]||
   Lookup[row,"EndpointDistributionIncluded",None]=!=False||
   !AssociationQ[Lookup[row,"Coefficients",None]],Return[False]];
 range=definition["EpsilonRange"];labels=Lookup[row,"StructureFunctions",{}];
 keys=Flatten[Table[{j,k},{j,Length[labels]},{k,First[range],Last[range]}],1];
 labels=!={}&&Lookup[row,"EpsilonRange",None]===range&&ContainsAll[Keys[row["Coefficients"]],keys]&&
  TrueQ[Lookup[Lookup[row,"IntegrationEndpointProof",<||>],"WholeEnergyIntervalVerified",False]]&&
  TrueQ[Lookup[row["IntegrationEndpointProof"],"ExternalPrescriptionLimitEstablished",False]]
];
PrepareMeasuredCurrentOneLoopContribution[card_Association,mode_String:"resume"]:=Catch[Module[
 {setup,request,geometry,specification,definition,path,file,saved,source,coordinates,kin,
  reduced,normalized,terms,noncontact={},contacts={},one,weight,e=Global`Epsilon,
  total,s,particles,prefactor,seconds,timings=<||>,output},
 If[!MemberQ[{"all","resume"},mode]||Lookup[card["Assembly"],"IntegrationMethod",None]=!="PolynomialMeasurement",
  projectFail["MeasuredOneLoopPreparationRequestRequired"]];
 particles=Take[card["FinalMomenta"],Length[card["UnobservedPartons"]]];
 If[Length[particles]=!=3||Lookup[card["Channels"][card["Channel"]],"Incoming",{}]=!={}||
   Lookup[card,"IncomingMomenta",{}]=!={}||
   Lookup[card["Channels"][card["Channel"]],"Observed",None]=!=None,
  projectFail["ThreeParticleOneLoopTreeDecayRequired"]];
 setup=projectCheck[FeynFacet`ReadProcessCard[card],"MeasuredCurrentProcessRequired"];
 If[{setup["ForwardAmplitudes"]["LoopOrder"],setup["ConjugateAmplitudes"]["LoopOrder"]}=!={1,0},
  projectFail["ThreeParticleOneLoopTreeDecayRequired"]];
 request=projectCheck[FeynFacet`ProjectAssemblyRequest[card],"MeasuredCurrentAssemblyRequired"];
 geometry=Join[card["Assembly"]["PhaseSpace"],<|"Name"->measuredOneLoopPhaseSpace,"FinalMomenta"->particles|>];
 specification=card["Assembly"]["FinalStateMeasurement"];path=card["WorkDirectory"];
 definition=<|"ProcessDefinition"->setup,"AssemblyRequest"->request,"PhaseSpace"->geometry,
  "FinalStateMeasurement"->specification,"SymmetryFactor"->Lookup[card,"SymmetryFactor",1],
  "FlavorMultiplicity"->Lookup[card,"FlavorMultiplicity",1]|>;
 file=path<>"/PreparedScalarLoopDensity.wl";
 If[mode=!="all"&&FileExistsQ[file],saved=FeynFacet`FamilyArtifactRead[file];
  If[AssociationQ[saved]&&Lookup[saved,"CalculationDefinition",None]===definition,
   Return[Join[saved,<|"Reused"->True,"StageSeconds"-><||>|>],Module]]];
 {seconds,source}=facetElapsedTiming[FeynFacet`ConstructCurrentIntegrands[setup,Join[request,
  <|"PrintTimings"->True,"KernelCount"->card["Execution"]["Kernels"]|>]]];
 source=projectCheck[source,"MeasuredCurrentGenerationFailed"];
 AssociateTo[timings,"AmplitudeGenerationAndContraction"->seconds];projectWrite[source,path<>"/Integrands.wl"];
 If[!TrueQ[Lookup[source,"FullDimensionScalarProducts",False]],projectFail["FullDimensionalMeasurementNumeratorRequired"]];
 total=geometry["TotalMomentum"];s=FeynCalc`FCI[FeynCalc`SPD[total]]/.FeynCalc`FCI[geometry["KinematicRules"]];
 coordinates=projectCheck[FeynFacet`MasslessInvariantPhaseSpaceCoordinates[particles,total,s,e,
   {measuredLoopFraction1,measuredLoopFraction2}],"MeasuredLoopPhysicalCoordinatesRequired"];
 kin=<|"ExternalMomenta"->particles,"MomentumRules"->{total->Total[particles]},
  "KinematicRules"->coordinates["ScalarProductRules"],"Assumptions"->coordinates["PhysicalDomain"],"DimensionalRegulator"->e|>;
 {seconds,reduced}=facetElapsedTiming[FeynFacet`ReduceOneLoopIntegrands[source["Values"],kin,
  <|"LoopMomentum"->First[setup["ForwardAmplitudes"]["LoopMomenta"]],"PrintTimings"->True|>]];
 reduced=projectCheck[reduced,"MeasuredLoopScalarReductionFailed"];
 AssociateTo[timings,"ScalarLoopReduction"->seconds];
 projectWrite[Join[reduced,<|"ProcessDefinition"->setup,"InvariantCoordinates"->coordinates|>],path<>"/MeasuredScalarLoopIntegrals.wl"];
 normalized=Join[reduced,Association@Table[key->Map[
   FeynFacet`SubstituteScalarPowers[#/.D->4-2e,request["BareCouplingRules"]]&,reduced[key]],{key,{"Values","InteriorValues"}}]];
 prefactor=(request["CurrentNormalization"]Lookup[card,"SymmetryFactor",1]Lookup[card,"FlavorMultiplicity",1])/.D->4-2e;
 {seconds,terms}=facetElapsedTiming[FeynFacet`CreateFinalStateMeasurementDefinitions[geometry,specification]];
 If[!ListQ[terms],projectFail["MeasuredLoopTupleDefinitionsRequired",<|"Cause"->terms|>]];
 AssociateTo[timings,"MeasurementDefinitions"->seconds];
 {seconds,one}=facetElapsedTiming[Do[
  If[term["Definition"]["ContactMeasurements"]==={},
   one=projectCheck[FeynFacet`ConstructOneLoopMeasurementDensity[normalized,coordinates,term["Definition"],
     <|"Parameters"->{measuredLoopEnergy1,measuredLoopEnergy2},"Weight"->term["Weight"],
       "ParticleOrder"->Join[DeleteDuplicates[First[term["ParticleTuples"]]],
          Complement[Range[Length[particles]],First[term["ParticleTuples"]]]],
       "DensityPrefactor"->prefactor,"Assumptions"->geometry["Assumptions"]&&
          And@@(0<#<1&/@card["Assembly"]["Variables"])|>],"MeasuredScalarLoopPushforwardFailed"];
   AppendTo[noncontact,Join[one,<|"ParticleTuples"->term["ParticleTuples"]|>]],
   weight=Factor[term["Weight"]/.coordinates["ScalarProductRules"]];
   If[!FreeQ[weight,_FeynCalc`Pair|_FeynCalc`Momentum],projectFail["InclusiveScalarLoopWeightRequired"]];
   AppendTo[contacts,Join[term,<|"Values"->Map[# weight prefactor coordinates["Density"]&,normalized["InteriorValues"]],
    "InvariantCoordinates"->coordinates,"PhysicalDomain"->coordinates["PhysicalDomain"],
    "ExternalPropagatorInteriorValues"->reduced["ExternalPropagatorInteriorValues"],
    "VirtualPrescriptionRemoved"->False,"EndpointContinuationRequired"->True,"IntegralEvaluated"->False|>]]],
 {term,terms}];Null];
 AssociateTo[timings,"ScalarMeasurementPushforwards"->seconds];
 output=<|"Format"->"FeynFacet-PreparedMeasuredOneLoopContribution","CalculationDefinition"->definition,
  "NoncontactTerms"->noncontact,"ContactTerms"->contacts,"StageSeconds"->timings,
  "Reused"->False,"ConjugateInterferenceAdded"->False,"EndpointDistributionsSolved"->False,
  "Scope"->"One causal amplitude orientation, before integration and addition of its complex conjugate. All tuple weights and generated state factors are included. No accepted hard coefficient is supplied by this representation."|>;
 projectWrite[output,file];output
],"ProjectCards"];
IntegrateMeasuredCurrentOneLoopInterior[card_Association,mode_String:"resume"]:=Catch[Module[
 {prepared,path,range,rows={},row,file,saved,definition,seconds,timings={},output,coefficients,labels=None,request,density},
 prepared=projectCheck[FeynFacet`PrepareMeasuredCurrentOneLoopContribution[card,mode],"PreparedMeasuredLoopContributionRequired"];
 path=card["WorkDirectory"];range=card["EpsilonRange"];
 request=<|"TimeLimit"->180,"PrintTimings"->True,"ConjugateInterference"->True,
   "Assumptions"->card["Assembly"]["Assumptions"],
   "ComplexParameters"->Lookup[prepared["CalculationDefinition"]["ProcessDefinition"],"ComplexParameters",{}]|>;
 Do[
  density=prepared["NoncontactTerms"][[i]];
  definition=<|"CalculationDefinition"->prepared["CalculationDefinition"],
   "ParticleTuples"->density["ParticleTuples"],"EpsilonRange"->range,"IntegrationSchema"->2,
   "Conjugation"->KeyTake[request,{"ConjugateInterference","Assumptions","ComplexParameters"}]|>;
  file=path<>"/IntegratedScalarLoopRow"<>ToString[i]<>".wl";saved=None;
  If[mode=!="all"&&FileExistsQ[file],saved=FeynFacet`FamilyArtifactRead[file]];
  If[measuredLoopInteriorReusableQ[saved,definition,density],row=saved;seconds=0,
   {seconds,row}=AbsoluteTiming[FeynFacet`IntegrateOneLoopMeasurementInterior[density,range,request]];
   row=projectCheck[row,"MeasuredLoopInteriorIntegrationFailed"];
   (* Exact input equality binds reuse to the actual prepared mathematics.
      The existing binary companion stores this input without text duplication
      or a new content hash. *)
   row=Join[row,<|"IntegrationDefinition"->definition,"ParticleTuples"->definition["ParticleTuples"],"TotalSeconds"->seconds,
     "InputCompanions"-><|"Density"->density|>|>];
   projectWrite[row,file]];
  If[labels===None,labels=row["StructureFunctions"]];
  If[labels=!=row["StructureFunctions"],projectFail["CommonMeasuredLoopStructuresRequired"]];
  AppendTo[rows,row["Coefficients"]];AppendTo[timings,<|"Row"->i,"Seconds"->seconds,"Record"->file,
    "Reused"->(seconds===0)|>],{i,Length[prepared["NoncontactTerms"]]}];
 coefficients=If[rows==={},<||>,Merge[rows,Total]];
 output=<|"Format"->"FeynFacet-MeasuredCurrentOneLoopInterior","Coefficients"->coefficients,
  "StructureFunctions"->If[labels===None,card["StructureFunctions"],labels],
  "DimensionalRegulator"->Global`Epsilon,"EpsilonRange"->range,
  "Variables"->card["Assembly"]["Variables"],"CalculationDefinition"->prepared["CalculationDefinition"],
  "PreparationTimings"->prepared["StageSeconds"],"IntegrationTimings"->timings,
  "ConjugateInterferenceAdded"->True,"EndpointDistributionIncluded"->False,
  "Scope"->"Explicit Hermitian Laurent coefficients on the open measurement domain. Self contacts and measurement-variable endpoint distributions remain separate."|>;
 projectWrite[output,path<>"/MeasuredOneLoopInterior.wl"];output
],"ProjectCards"];
VerifyMeasuredCurrentOneLoopContactOrder[card_Association,mode_String:"resume"]:=Catch[Module[
 {prepared,file,saved,definition,inputs,rows={},seconds,proof,output,moments},
 prepared=projectCheck[FeynFacet`PrepareMeasuredCurrentOneLoopContribution[card,mode],"PreparedMeasuredLoopContributionRequired"];
 file=card["WorkDirectory"]<>"/MeasuredContactOrder.wl";
 definition=<|"CalculationDefinition"->prepared["CalculationDefinition"],"ContactDerivativeOrder"->0,
   "Assumptions"->card["Assembly"]["Assumptions"]|>;
 inputs=prepared["NoncontactTerms"];
 moments=projectCheck[FeynFacet`ConstructFinalStateMeasurementMoments[
   prepared["CalculationDefinition"]["PhaseSpace"],prepared["CalculationDefinition"]["FinalStateMeasurement"],{0,1}],
   "GeneratedInclusiveMeasurementMomentWeightsRequired"];
 If[mode=!="all"&&FileExistsQ[file],saved=FeynFacet`FamilyArtifactRead[file];
  If[AssociationQ[saved]&&Lookup[saved,"Format",None]==="FeynFacet-MeasuredCurrentContactOrder"&&
    Lookup[saved,"CalculationDefinition",None]===definition&&
    Lookup[Lookup[saved,"InputCompanions",<||>],"Densities",None]===inputs&&
    Length[Lookup[saved,"Rows",{}]]===Length[inputs]&&
    AllTrue[Lookup[saved,"Rows",{}],TrueQ[Lookup[#["Proof"],"CompleteEnergyMeasurementCoverVerified",False]]&&
      Lookup[#["Proof"],"ContactDerivativeOrderBound",None]===0&],
   output=Join[saved,<|"MeasurementMoments"->moments,"Reused"->True|>];
   If[Lookup[saved,"MeasurementMoments",None]=!=moments,projectWrite[output,file]];
   Return[output,Module]]];
 Do[
  {seconds,proof}=AbsoluteTiming[FeynFacet`VerifyOneLoopMeasurementContactOrder[inputs[[i]],0,
    <|"Assumptions"->card["Assembly"]["Assumptions"],"PrintTimings"->True|>]];
  proof=projectCheck[proof,"MeasuredContactOrderProofFailed"];
  AppendTo[rows,<|"Row"->i,"ParticleTuples"->inputs[[i]]["ParticleTuples"],
    "Proof"->proof,"Seconds"->seconds|>],{i,Length[inputs]}];
 output=<|"Format"->"FeynFacet-MeasuredCurrentContactOrder","CalculationDefinition"->definition,
  "ContactDerivativeOrderBound"->0,"Rows"->rows,"MeasurementMoments"->moments,"Reused"->False,
  "InputCompanions"-><|"Densities"->inputs|>,"ContactCoefficientsDetermined"->False,
  "Scope"->"Every noncontact tuple group has only ordinary endpoint contact ambiguities after extending its computed interior. Its conjugate obeys the same bound. Explicit self pairs retain their separately declared contact support; they must not be counted twice in subsequent moment completion."|>;
 projectWrite[output,file];output
],"ProjectCards"];
End[];EndPackage[];
