(* Card-owned counterterm distributions and the native NLO project workflow. *)
BeginPackage["FeynFacet`"];
PlanNLOCounterterms::usage="PlanNLOCounterterms[channelDirectory] resolves each declared counterterm distribution and derives the epsilon orders of automatically regenerated Born sources from its Laurent lower bound. No lower-order card or result is read.";
ConstructNLOCountertermContribution::usage="ConstructNLOCountertermContribution[compiledCard] regenerates the required Born source and evaluates one ordinary counterterm contribution from its PDF, FF and coupling insertions. ConstructNLOCountertermContribution[compiledCard,bornSources] accepts already generated channel-to-result associations with sufficient epsilon orders.";
Begin["`Private`"];
projectCountertermLegs[card_Association]:=Module[{legs},
 legs=Lookup[card["Assembly"],"FactorizationLegs",None];
 If[!AssociationQ[legs]||legs===<||>,projectFail["DeclaredFactorizationLegsRequired"]];
 legs
];

projectCountertermRawSchemes[card_Association]:=Association@KeyValueMap[Function[{leg,definition},
 leg->Lookup[Lookup[card,"BareOperatorSchemes",<||>],leg,
  If[If[definition["Role"]==="PDF",card["Polarization"]["Incoming"][[definition["Index"]]],
    card["Polarization"]["Observed"]]==="L","Larin","MSbar"]]
],projectCountertermLegs[card]];

projectNLOCountertermInsertion[card_Association,leg_String,insertion_Association]:=Module[
 {ct,source,target,legs,definition,role,index,spin,daughter,parent,raw,targetScheme,finite,
  spec,distribution,e=Global`Epsilon,poleNormalization,couplingRenormalization,power,scalar,bound,weight,allowed},
 ct=card["Counterterms"];source=card["Channels"][card["SourceChannel"]];target=card["Channels"][card["Channel"]];
 If[Lookup[insertion,"PerturbativeOrder",None]=!=1,
  projectFail["NLOCountertermInsertionOrderRequired"]];
 allowed={"Distribution","PerturbativeOrder","Operation","FlavorMultiplicity","PoleNormalization",
   "ScaleLog","OperatorScheme","OperatorRedefinition","KernelParameters","Spin","Variable"};
 If[!SubsetQ[allowed,Keys[insertion]],projectFail["UnsupportedCountertermInsertionFields",
   <|"Fields"->Complement[Keys[insertion],allowed]|>]];
 weight=Lookup[insertion,"FlavorMultiplicity",1];
 If[!FreeQ[{weight,Lookup[card,"FlavorMultiplicity",1]},e|_Real|_Missing|_Failure|Indeterminate|_DirectedInfinity]||
   !FreeQ[{weight,Lookup[card,"FlavorMultiplicity",1]},Alternatives@@card["Assembly"]["Variables"]],
  projectFail["ExactEpsilonIndependentMultiplicityRequired"]];
 poleNormalization=Lookup[ct,"PoleNormalization",Missing["PoleNormalization"]];
 If[MissingQ[poleNormalization],projectFail["DeclaredCountertermPoleNormalizationRequired"]];
 If[leg==="Coupling",
  If[Lookup[insertion,"Distribution",None]=!="CouplingCounterterm"||source=!=target||
    Lookup[card,"SourceRenormalizationStage","Bare"]=!="Bare"||
    Lookup[insertion,"Operation",None]=!="CollinearSubtraction"||
    !SubsetQ[{"Distribution","PerturbativeOrder","Operation","FlavorMultiplicity"},Keys[insertion]],
   projectFail["SameChannelBareCouplingCountertermRequired"]];
  power=card["BornCouplingPower"];
  If[!IntegerQ[power]||power<0,projectFail["NonnegativeBornCouplingPowerRequired"]];
  couplingRenormalization=projectCheck[FeynFacet`MSbarCouplingRenormalization[
    ct["KernelParameters"],ct["CouplingNormalization"]],"CouplingRenormalizationCoefficientsRequired"];
  scalar=power couplingRenormalization[1];
  bound=FeynFacet`DetermineMeromorphicLaurentLowerBound[scalar,e];
  If[!IntegerQ[bound]&&bound=!=Infinity,projectFail["CouplingCountertermLaurentOrderRequired",<|"Cause"->bound|>]];
  Return[<|"Leg"->leg,"Distribution"-><|"Role"->"Coupling","PerturbativeOrder"->1,
    "ScalarCoefficient"->scalar,"DimensionalRegulator"->e,"LaurentLowerBound"->bound|>,
    "FlavorMultiplicity"->weight|>]];
 legs=projectCountertermLegs[card];definition=Lookup[legs,leg,None];
 If[!AssociationQ[definition],projectFail["DeclaredCountertermLegRequired",<|"Leg"->leg|>]];
 role=Lookup[definition,"Role",None];
 If[!MemberQ[{"PDF","FF"},role]||
    Lookup[insertion,"Distribution",None]=!=role<>"Counterterm",
  projectFail["CountertermDistributionMustMatchPhysicalLeg",<|"Leg"->leg|>]];
 If[role==="PDF",
  index=Lookup[definition,"Index",None];
  If[!IntegerQ[index]||index<1||index>Length[target["Incoming"]]||
    Length[source["Incoming"]]=!=Length[target["Incoming"]]||
    Lookup[source,"Observed",None]=!=Lookup[target,"Observed",None]||
    ReplacePart[source["Incoming"],index->target["Incoming"][[index]]]=!=target["Incoming"],
   projectFail["OnlyInsertedPDFLegMayChangeSourceChannel",<|"Leg"->leg|>]];
  {daughter,parent}={source["Incoming"][[index]],target["Incoming"][[index]]};
  spin=card["Polarization"]["Incoming"][[index]],
  If[source["Incoming"]=!=target["Incoming"]||!ContainsAll[Keys[source],{"Observed"}]||
    !ContainsAll[Keys[target],{"Observed"}],projectFail["OnlyInsertedFFLegMayChangeSourceChannel"]];
  {daughter,parent}={target["Observed"],source["Observed"]};spin=card["Polarization"]["Observed"]];
 raw=projectCountertermRawSchemes[card][leg];
 If[Lookup[insertion,"Spin",spin]=!=spin||Lookup[insertion,"Variable",definition["Variable"]]=!=definition["Variable"]||
   Lookup[insertion,"KernelParameters",ct["KernelParameters"]]=!=ct["KernelParameters"],
  projectFail["CountertermOperatorMustPreservePhysicalSpinCoordinatesAndQCDParameters"]];
 If[Lookup[insertion,"PoleNormalization",poleNormalization]=!=poleNormalization,
  projectFail["CountertermPoleNormalizationMustMatchDeclaredBareCoupling"]];
 If[(Lookup[insertion,"Operation","Factorization"]==="CollinearSubtraction"&&KeyExistsQ[insertion,"OperatorRedefinition"])||
   (Lookup[insertion,"Operation","Factorization"]==="FiniteSchemeChange"&&KeyExistsQ[insertion,"OperatorScheme"]),
  projectFail["RawAndFiniteOperatorSchemeFieldsMustBeSeparate"]];
 targetScheme=ct["Schemes"][leg];
 finite=If[KeyExistsQ[insertion,"OperatorRedefinition"],insertion["OperatorRedefinition"],Which[
   Lookup[insertion,"Operation","Factorization"]==="CollinearSubtraction"||raw===targetScheme,"MSbar",
   raw==="Larin"&&(targetScheme==="HelicityMSbar"||
     (AssociationQ[targetScheme]&&Lookup[targetScheme,"DefaultScheme","MSbar"]==="HelicityMSbar")),targetScheme,
   raw==="MSbar"&&AssociationQ[targetScheme]&&Lookup[targetScheme,"DefaultScheme","MSbar"]==="MSbar",targetScheme,
   True,projectFail["ExplicitFiniteOperatorSchemeRelationRequired",<|"SourceScheme"->raw,"TargetScheme"->targetScheme|>]]];
 spec=Join[<|"Spin"->spin,"Variable"->definition["Variable"],"DimensionalRegulator"->e,
   "KernelParameters"->ct["KernelParameters"],"PerturbativeOrder"->1,
   "ScaleLog"->Log[ct["FactorizationScalesSquared"][leg]]-Log[ct["RenormalizationScaleSquared"]],
   "OperatorScheme"->raw,"OperatorRedefinition"->finite,"PoleNormalization"->poleNormalization,
   "Operation"->"Factorization","SourceRenormalizationStage"->Lookup[card,"SourceRenormalizationStage","Bare"]|>,
  KeyDrop[insertion,{"Distribution","FlavorMultiplicity"}]];
 If[spec["OperatorScheme"]=!=raw,
  projectFail["CountertermOperatorSchemeMustMatchSource",<|"SourceScheme"->raw,"OperatorScheme"->spec["OperatorScheme"]|>]];
 distribution=projectCheck[If[role==="PDF",FeynFacet`PDFCountertermDistribution[daughter,parent,spec],
   FeynFacet`FFCountertermDistribution[daughter,parent,spec]],"CountertermDistributionConstructionFailed"];
 If[distribution["SourceRenormalizationStage"]=!=Lookup[card,"SourceRenormalizationStage","Bare"],
  projectFail["CountertermSourceRenormalizationStageMismatch"]];
 <|"Leg"->leg,"Daughter"->daughter,"Parent"->parent,"Spin"->spin,"Scheme"->targetScheme,
  "Distribution"->distribution,"FlavorMultiplicity"->weight|>
];

PlanNLOCounterterms[directory_String]:=Catch[
 projectPlanNLOCountertermCards[projectCheck[FeynFacet`ReadCountertermCards[directory],"CountertermCardsRequired"]],"ProjectCards"];

projectPlanNLOCountertermCards[cards_Association]:=Catch[Module[
 {first,rows={},orders=<||>,card,products,insertion,leg,row,bound,through,source,definitions},
 If[!AssociationQ[cards]||cards===<||>,projectFail["NonemptyCountertermCardsRequired"]];
 first=First[Values[cards]];
 KeyValueMap[Function[{name,entry},
  card=entry;
  If[card["Order"]=!="NLO"||Lookup[card,"SourceOrder",None]=!="LO"||
    !KeyExistsQ[card["Channels"],Lookup[card,"SourceChannel",None]],
   projectFail["NLOCountertermWithDeclaredBornSourceRequired",<|"CardName"->name|>]];
  If[!MemberQ[{"Bare","Renormalized"},Lookup[card,"SourceRenormalizationStage","Bare"]],
   projectFail["NLOCountertermSourceRenormalizationStageRequired",<|"CardName"->name|>]];
  If[!MatchQ[Lookup[card,"EpsilonRange",None],{_Integer,_Integer}]||
    First[card["EpsilonRange"]]>Last[card["EpsilonRange"]]||Last[card["EpsilonRange"]]<0,
   projectFail["CountertermEpsilonRangeRequired"]];
  If[Lookup[card,"SourceRenormalizationStage","Bare"]==="Renormalized"&&card["EpsilonRange"]=!={0,0},
   projectFail["FiniteSchemeDefinesOnlyEpsilonZero"]];
  source=card["SourceChannel"];
  definitions=Lookup[Lookup[card["BareSourceContributions"],"LO",<||>],source,None];
  If[!AssociationQ[definitions]||!KeyExistsQ[definitions,"Born"],
   projectFail["SharedBornSourcePhysicsRequired",<|"SourceChannel"->source|>]];
  products=Lookup[card,"OperatorInsertions",None];
  If[!ListQ[products]||products==={}||!AllTrue[products,AssociationQ[#]&&Length[#]===1&],
   projectFail["SingleFirstOrderInsertionPerNLOTermRequired",<|"CardName"->name|>]];
  Do[
   leg=First[Keys[product]];insertion=First[Values[product]];
   If[!StringQ[leg]||!AssociationQ[insertion],projectFail["CountertermInsertionAssociationRequired"]];
   row=projectNLOCountertermInsertion[card,leg,insertion];bound=row["Distribution"]["LaurentLowerBound"];
   If[Last[card["EpsilonRange"]]>Lookup[row["Distribution"],"MaximumDefinedEpsilonOrder",Infinity],
    projectFail["FiniteSchemeDefinesOnlyEpsilonZero"]];
   If[!IntegerQ[bound]&&bound=!=Infinity,projectFail["CountertermLaurentLowerBoundRequired"]];
   If[IntegerQ[bound]&&First[card["EpsilonRange"]]>bound,
    projectFail["CountertermEpsilonRangeOmitsRequiredPoles",<|"CardName"->name,"LaurentLowerBound"->bound|>]];
   through=If[bound===Infinity,Last[card["EpsilonRange"]],Max[0,Last[card["EpsilonRange"]]-bound]];
   AssociateTo[orders,source->Max[through,Lookup[orders,source,0]]];
   AppendTo[rows,Join[row,<|"CardName"->name,"BornChannelName"->source,
     "RequiredSourceThroughOrder"->through,"EpsilonRange"->card["EpsilonRange"]|>]],
  {product,products}]
 ],cards];
 <|"Project"->first["Project"],"Order"->"NLO","Channel"->first["Channel"],
  "CountertermCards"->cards,"CountertermDistributions"->rows,"BornSourceOrders"->orders,
  "Reason"->"Each source epsilon upper order is the requested counterterm upper order minus the distribution Laurent lower bound; the required bare amplitudes are regenerated in the consuming channel."|>
],"ProjectCards"];

ConstructNLOCountertermContribution[card_Association,borns_Association]:=Catch[Module[{name,plan,results},
 name=Lookup[card,"CardName",None];
 If[!StringQ[name],projectFail["CompiledCountertermContributionCardRequired"]];
 plan=projectCheck[projectPlanNLOCountertermCards[<|name->card|>],"NLOCountertermPlanFailed"];
 If[!ContainsAll[Keys[borns],Keys[plan["BornSourceOrders"]]],projectFail["RequiredBornSourcesMissing"]];
 results=projectNLOCountertermResults[plan,borns];results[name]
],"ProjectCards"];

ConstructNLOCountertermContribution[card_Association]:=Catch[Module[{name,plan,generated,results},
 name=Lookup[card,"CardName",None];
 If[!StringQ[name],projectFail["CompiledCountertermContributionCardRequired"]];
 plan=projectCheck[projectPlanNLOCountertermCards[<|name->card|>],"NLOCountertermPlanFailed"];
 generated=projectCheck[FeynFacet`GenerateBornPartonicSources[card,plan["BornSourceOrders"]],"AutomaticBornSourcesFailed"];
 results=projectNLOCountertermResults[plan,generated["Results"]];
 Join[results[name],<|"BornSourceOrders"->plan["BornSourceOrders"],
   "GeneratedSources"->generated["GeneratedSources"],"SourceGenerationSeconds"->generated["StageSeconds"]|>]
],"ProjectCards"];

projectNLOCountertermSource[born_Association,card_Association]:=Module[{schemes,value},
 If[Lookup[card,"SourceRenormalizationStage","Bare"]==="Bare",Return[born]];
 schemes=projectCountertermRawSchemes[card];
 If[Lookup[born,"Order",None]=!="LO"||Lookup[born,"LaurentLowerBound",-1]<0||
   FeynFacet`RequirePartonicEpsilonRange[born,{0,0}]=!=True||
   TrueQ[Lookup[born,"FiniteSchemeConversionApplied",False]],
  projectFail["PoleFreeLOSourceBeforeFiniteSchemeChangeRequired"]];
 If[Lookup[born,"RenormalizationStage",None]==="Renormalized",
  If[!TrueQ[Lookup[born,"RawSchemePoleCancellation",False]]||Lookup[born,"OperatorSchemes",None]=!=schemes,
   projectFail["MatchingRawSubtractedLOSourceRequired"]];Return[born]];
 If[Lookup[born,"RenormalizationStage",None]=!="Bare",projectFail["BareOrRawSubtractedLOSourceRequired"]];
 (* At relative order zero raw UV and collinear subtraction are the identity.
    The finite scheme acts only on its verified epsilon-zero coefficient. *)
 value=FeynFacet`CreatePartonicResult[KeyTake[born["Coefficients"],{0}],
  Join[KeyDrop[born,{"Coefficients","EpsilonRange","LaurentLowerBound"}],
   <|"RenormalizationStage"->"Renormalized","RawSchemePoleCancellation"->True,
     "FiniteSchemeConversionApplied"->False,
     "OperatorSchemes"->schemes,"RawSubtractionAtLO"->"Identity"|>]];
 projectCheck[value,"RawSubtractedLOSourceRequired"]
];

projectNLOCountertermResults[plan_Association,borns_Association]:=Module[
 {results=<||>,card,request,rows,parts,value,born,distribution,meta},
 KeyValueMap[Function[{name,entry},
  card=entry;request=Join[FeynFacet`ProjectAssemblyRequest[card],
    <|"EpsilonRange"->card["EpsilonRange"],"PerturbativeParameter"->card["Counterterms"]["Coupling"]/(2Pi),
      "Convolution"->card["Assembly"]["CollinearConvolution"]|>];
  rows=Select[plan["CountertermDistributions"],#["CardName"]===name&];parts=<||>;
  Do[
   born=borns[row["BornChannelName"]];distribution=row["Distribution"];
   If[!AssociationQ[born],projectFail["BornSourceResultRequired"]];
   born=projectNLOCountertermSource[born,card];
   If[!AssociationQ[born]||Lookup[born,"Order",None]=!="LO"||
     Lookup[born,"PhysicalChannel",None]=!=card["Channels"][row["BornChannelName"]]||
     Lookup[born,"Polarization",None]=!=card["Polarization"]||Lookup[born,"Project",None]=!=card["Project"]||
     Lookup[born,"CouplingPower",None]=!=card["BornCouplingPower"]||
     Lookup[born,"Coupling",None]=!=request["Coupling"]||
     Lookup[born,"CouplingNormalization",None]=!=card["Counterterms"]["CouplingNormalization"]||
     Lookup[born,"DimensionalPrefactor",None]=!=request["DimensionalPrefactor"]||
     Lookup[born,"RenormalizationStage",None]=!=Lookup[card,"SourceRenormalizationStage","Bare"],
    projectFail["CountertermBornSourceIdentityMismatch",<|"CardName"->name,"SourceChannel"->row["BornChannelName"]|>]];
   If[row["Leg"]==="Coupling",
    value=FeynFacet`MultiplyPartonicLaurentFactor[born,
      request["PerturbativeParameter"] distribution["ScalarCoefficient"],card["EpsilonRange"]],
    value=FeynFacet`ApplyCountertermDistribution[born,distribution,Join[request,<|"Leg"->row["Leg"]|>,
     If[KeyExistsQ[Lookup[card["Assembly"],"CollinearMaps",<||>],row["Leg"]],
      <|"CollinearMap"->card["Assembly"]["CollinearMaps"][row["Leg"]]|>,<||>]]]];
   value=projectCheck[value,"CountertermDistributionApplicationFailed"];
   meta=Join[KeyDrop[value,{"Coefficients","EpsilonRange","LaurentLowerBound","ProcessDefinition"}],
     KeyTake[request,{"Project","Channel","PhysicalChannel","Polarization","Coupling","CouplingPower"}],
     <|"Order"->"NLO","Contribution"->"Counterterm","CardName"->name,"RenormalizationStage"->"Counterterm"|>];
   value=projectCheck[FeynFacet`CreatePartonicResult[value["Coefficients"],meta],"CountertermResultIdentityFailed"];
   value=projectWeightedPartonicResult[value,row["FlavorMultiplicity"]];
   AssociateTo[parts,IntegerString[Length[parts]+1]->value],
  {row,rows}];
  value=projectCheck[FeynFacet`CombinePartonicResults[parts,<|"Contribution"->"Counterterm","CardName"->name,
    "SourceOrder"->card["SourceOrder"],"SourceChannel"->card["SourceChannel"],
    "OperatorInsertions"->card["OperatorInsertions"],"CountertermDistributions"->Lookup[rows,"Distribution"],
    "RenormalizationStage"->"Counterterm"|>],"CountertermCardCombinationFailed"];
  value=projectWeightedPartonicResult[value,Lookup[card,"FlavorMultiplicity",1]];
  If[FeynFacet`RequirePartonicEpsilonRange[value,card["EpsilonRange"]]=!=True,
   projectFail["CountertermCardEpsilonOrdersInsufficient",<|"CardName"->name,"Required"->card["EpsilonRange"]|>]];
  AssociateTo[results,name->value]
 ],plan["CountertermCards"]];results
];


End[];EndPackage[];
