(* FeynFacet/Private/Core/Algebra/Radicals.wl -- split out of Core/Base/Core.wl in round 5
   (2026-09-02, substructure ruling): algebraic letters -- radicals of the spectator:
   the square-free radical canon, the radical normalizer and the exact zero
   decision over the extension generated by the radicals
   (masterTransportRadical*; the zero tests that use them stay in Base).
   Verbatim moves of whole top-level statements; loads after Base/Core.wl
   (Private/LoadOrder.wl), inside the FeynFacet`Private` context. *)

Begin["FeynFacet`Private`"];

ClearAll[
  masterTransportRadicalQ,
  masterTransportRadicalCanon,
  masterTransportRadicalNormalize,
  masterTransportRadicalZeroQ
];

(* ---- algebraic letters: radicals of the spectator ---------------------

   MEASURED 2026-08-17 (Scripts/... monic probes over all 91 families):
   the canonical alphabets contain letters that are QUADRATIC in the
   moving path variable with a discriminant that is not a square in the
   frozen variable -- 1 - w + v w pulled back to the class-97 chart is a
   (2,2)-curve on P^1 x P^1 (genus 1), so NO rational chart makes it
   linear.  Such a letter contributes the two roots

       tau_+- = (-b +- k Sqrt[D0]) / (2 a),     b^2 - 4 a c = k^2 D0,

   D0 square-free, to the word alphabet: G(tau_+, ...; tau) with an
   ALGEBRAIC index in the frozen variable -- the ordinary fibration
   representation of multivariate polylogarithms.  Libra's Pexp admits
   such poles natively (its PolesPosition is Solve[den == 0, x]); the
   monic gate below used to refuse them by policy, not by mathematics.

   Two disciplines make the arithmetic exact:

     (1) every radical is written as k Sqrt[D0] with D0 the SQUARE-FREE
         part of the discriminant (numeric content left to the kernel's
         own automatic normalization), so that equal extensions are
         syntactically equal and letters from different quadratics with
         the same D0 live in the same field;
     (2) a zero test that DECIDES over Q(vars, Sqrt[D0_1], ...): the
         radicals are replaced by symbols r_i, the expression is written
         as one fraction, and the numerator is reduced modulo r_i^2 - D0_i;
         it is zero iff every remaining coefficient of the r-monomials is
         zero.  Together alone is NOT a decision procedure here (it does
         not know r^2 = D0 once the radical sits inside a denominator),
         which is why this exists.

   Nothing else changes: word indices remain tau-free constants, the
   append rule and the recursion certificate are unchanged, and a letter
   with an eps-DEPENDENT discriminant is refused (an apparent
   singularity that the off-diagonal cleanup must remove, never a
   letter). *)

masterTransportRadicalQ[e_] := ! FreeQ[e, Power[_, _Rational]];

(* k Sqrt[D0] with D0 square-free, for a polynomial (or rational) D *)
masterTransportRadicalCanon[d_] := Module[{t, num, den, fl, k, d0},
  t = Together[d];
  If[TrueQ[t === 0], Return[0]];
  num = Numerator[t]; den = Denominator[t];
  (* Sqrt[num/den] = Sqrt[num den]/den *)
  fl = FactorSquareFreeList[Expand[num den]];
  k = Times @@ Table[f[[1]]^Quotient[f[[2]], 2], {f, fl}];
  d0 = Times @@ Table[If[OddQ[f[[2]]], f[[1]], 1], {f, fl}];
  Together[k Sqrt[Expand[d0]]/den]];

(* rewrite every half-integer power inside e as (radical) with the
   square-free discipline; idempotent *)
masterTransportRadicalNormalize[e_] :=
  e /. Power[b_, q_Rational] /; Denominator[q] === 2 :>
    Module[{m = Numerator[q], r = masterTransportRadicalCanon[b]},
      (* b^(m/2) = b^((m-1)/2) Sqrt[b] for every odd m, positive or
         negative: 1/Sqrt[b] = Sqrt[b]/b, b^(-3/2) = Sqrt[b]/b^2 *)
      b^((m - 1)/2) r];

(* the decision procedure: True iff e vanishes identically over the
   extension generated by its radicals *)
masterTransportRadicalZeroQ[e_] := Module[
  {t, radicals, syms, rules, relations, num, poly, remainder, coefficients},
  t = Together[masterTransportRadicalNormalize[e]];
  If[TrueQ[t === 0], Return[True]];
  (* every half-integer power b^(m/2), m odd, positive or negative: the
     kernel folds b Sqrt[b] into b^(3/2) automatically, so the bases are
     collected from ALL such powers and each is rewritten as
     b^((m-1)/2) r  (r^2 = b), which covers 1/Sqrt[b] = r/b and
     b^(-3/2) = r/b^2 as well *)
  radicals = DeleteDuplicates[Cases[t,
    Power[b_, q_Rational] /; Denominator[q] === 2 :> b, {0, Infinity}]];
  If[radicals === {}, Return[False]];
  syms = Table[Unique["masterTransportRadical"], {Length[radicals]}];
  rules = Table[
    With[{b = radicals[[i]], s = syms[[i]]},
      Power[b, q_Rational] /; Denominator[q] === 2 :>
        b^((Numerator[q] - 1)/2) s],
    {i, Length[radicals]}];
  relations = Table[syms[[i]]^2 - radicals[[i]], {i, Length[radicals]}];
  t = Together[t /. rules];
  num = Numerator[t];
  (* clear any radical left in the denominator by multiplying through
     with the conjugates: den * conj is r-free after reduction *)
  Module[{den = Denominator[t], i = 1},
    While[! FreeQ[den, Alternatives @@ syms] && i <= 4 Length[syms],
      Module[{s = SelectFirst[syms, ! FreeQ[den, #] &], conj},
        conj = den /. s -> -s;
        num = PolynomialRemainder[Expand[num conj], relations[[Position[syms, s][[1, 1]]]], s];
        den = PolynomialRemainder[Expand[den conj], relations[[Position[syms, s][[1, 1]]]], s]];
      i++]];
  poly = Expand[num];
  remainder = poly;
  Do[remainder = PolynomialRemainder[remainder, relations[[i]], syms[[i]]],
    {i, Length[syms]}];
  remainder = Together[remainder];
  If[TrueQ[remainder === 0], Return[True]];
  (* the denominator is radical-free after the conjugation loop; the
     numerator is a polynomial of degree <= 1 in every r_i whose
     r-monomial coefficients must ALL vanish (1, r_i, r_i r_j, ... are
     linearly independent over the rational functions when the D0_i are
     square-free and pairwise non-proportional modulo squares) *)
  coefficients = CoefficientList[Numerator[remainder], syms];
  AllTrue[Flatten[coefficients], TrueQ[Together[#] === 0] &]
];

End[];
