<|"Prime" -> 2147483477, "SampleCount" -> 32, "ConstructionCount" -> 24, 
 "ValidationCount" -> 8, "MaximumTotalDegree" -> 22, 
 "NormalizationColumns" -> {9, 10, 11, 12, 13, 14, 15, 16}, 
 "GaugeUnknownCount" -> 8, "FreeResidueCount" -> 88, 
 "GaugeNumeratorDegrees" -> {0, 0}, "InterpolationSeconds" -> 0.002844, 
 "UnresolvedCoordinates" -> {}, "DegreeHistogram" -> 
  <|{-Infinity, 0} -> 96|>, "Interpolations" -> 
  {<|"Numerator" -> {0}, "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>, <|"Numerator" -> {0}, 
    "Denominator" -> {1}, "Degrees" -> {-Infinity, 0}, 
    "ConstructionNullity" -> 1, "ValidatedPointCount" -> 32, 
    "UniquenessPointRequirement" -> 1|>}|>
