<|
 "Status" -> "CF303InheritedSoftSourceNeedsV1",
 "Family" -> "CF303",
 "Scope" ->
  "Only the seven source-state coordinates seen by W=[T25.H,T25]; no raw 2x43 W is reconstructed",
 "Endpoint" -> <|
   "Stratum" -> "s=1-v-w=0", "NormalCoordinate" -> "rho=2p-u",
   "PhysicalSoftPoint" -> {v -> p^2, w -> 1 - p^2},
   "AcceptedSourceFrameSoftPoint" -> {x -> p^2, y -> 1 - p^2},
   "PhysicalToChartLeadingRelation" ->
    HoldForm[s == ((1 - 2*p^2)/(2*p))*rho + O[rho]^2]|>,
 "AcceptedStateSupportRows" -> {1, 2, 12, 21, 22, 29, 30},
 "StateToLowerPhysical" -> {
   <|"StateRow" -> 1, "SourceBlock" -> 1, "BlockComponent" -> 1,
     "CF303OriginalMaster" -> 7, "LowerFamily" -> "CF1",
     "LowerPhysicalRow" -> 1, "LowerCanonicalRow" -> 1,
     "ClassID" -> 1, "ChartAtSoft" -> {v -> p^2, w -> 1 - p^2},
     "CanonicalFromPhysicalFactor" -> 1/(-1 + x + y),
     "EpsilonLeadingShift" -> 0,
     "SourceBoundaryOrders" -> Range[0, 5],
     "RequiredLowerPhysicalOrders" -> Range[0, 5],
     "ExistingObservableOrders" -> Range[0, 5],
     "MissingObservableOrders" -> {}|>,
   <|"StateRow" -> 2, "SourceBlock" -> 2, "BlockComponent" -> 1,
     "CF303OriginalMaster" -> 39, "LowerFamily" -> "CF12",
     "LowerPhysicalRow" -> 4, "LowerCanonicalRow" -> 6,
     "ClassID" -> 5, "ChartAtSoft" -> {x -> p^2, y -> 1 - p^2},
     "CanonicalFromPhysicalFactor" ->
      (2*eps^3)/(-2 + 13*eps - 27*eps^2 + 18*eps^3),
     "EpsilonLeadingShift" -> 3,
     "SourceBoundaryOrders" -> Range[0, 5],
     "RequiredLowerPhysicalOrders" -> Range[0, 2],
     "ExistingObservableOrders" -> Range[0, 1],
     "MissingObservableOrders" -> {2}|>,
   <|"StateRow" -> 12, "SourceBlock" -> 11, "BlockComponent" -> 1,
     "CF303OriginalMaster" -> 8, "LowerFamily" -> "CF21",
     "LowerPhysicalRow" -> 1, "LowerCanonicalRow" -> 4,
     "ClassID" -> 17, "ChartAtSoft" -> {x -> -p, y -> p},
     "CanonicalFromPhysicalFactor" -> eps/(-2 + 3*eps),
     "EpsilonLeadingShift" -> 1,
     "SourceBoundaryOrders" -> Range[0, 5],
     "RequiredLowerPhysicalOrders" -> Range[0, 4],
     "ExistingObservableOrders" -> Range[0, 4],
     "MissingObservableOrders" -> {}|>,
   <|"StateRow" -> 21, "SourceBlock" -> 14, "BlockComponent" -> 1,
     "CF303OriginalMaster" -> 29, "LowerFamily" -> "CF199",
     "LowerPhysicalRow" -> 1, "LowerCanonicalRow" -> 8,
     "ClassID" -> 44, "ChartAtSoft" -> {x -> p^2, y -> 1 - p^2},
     "CanonicalFromPhysicalFactor" ->
      (2*eps^3)/(-2 + 13*eps - 27*eps^2 + 18*eps^3),
     "EpsilonLeadingShift" -> 3,
     "SourceBoundaryOrders" -> Range[-1, 5],
     "RequiredLowerPhysicalOrders" -> Range[0, 2],
     "ExistingObservableOrders" -> Range[0, 1],
     "MissingObservableOrders" -> {2}|>,
   <|"StateRow" -> 22, "SourceBlock" -> 14, "BlockComponent" -> 2,
     "CF303OriginalMaster" -> 30, "LowerFamily" -> "CF199",
     "LowerPhysicalRow" -> 2, "LowerCanonicalRow" -> 9,
     "ClassID" -> 44, "ChartAtSoft" -> {x -> p^2, y -> 1 - p^2},
     "CanonicalFromPhysicalFactor" ->
      (2*eps^2*(-1 + x))/(-2 + 13*eps - 27*eps^2 + 18*eps^3),
     "EpsilonLeadingShift" -> 2,
     "SourceBoundaryOrders" -> Range[-1, 5],
     "RequiredLowerPhysicalOrders" -> Range[0, 3],
     "ExistingObservableOrders" -> Range[0, 2],
     "MissingObservableOrders" -> {3}|>,
   <|"StateRow" -> 29, "SourceBlock" -> 18, "BlockComponent" -> 1,
     "CF303OriginalMaster" -> 20, "LowerFamily" -> "CF53",
     "LowerPhysicalRow" -> 4, "LowerCanonicalRow" -> 11,
     "ClassID" -> 44, "ChartAtSoft" -> {x -> -p, y -> p},
     "CanonicalFromPhysicalFactor" ->
      (2*eps^3)/(-2 + 13*eps - 27*eps^2 + 18*eps^3),
     "EpsilonLeadingShift" -> 3,
     "SourceBoundaryOrders" -> Range[-1, 5],
     "RequiredLowerPhysicalOrders" -> Range[0, 2],
     "ExistingObservableOrders" -> Range[0, 1],
     "MissingObservableOrders" -> {2}|>,
   <|"StateRow" -> 30, "SourceBlock" -> 18, "BlockComponent" -> 2,
     "CF303OriginalMaster" -> 21, "LowerFamily" -> "CF53",
     "LowerPhysicalRow" -> 5, "LowerCanonicalRow" -> 12,
     "ClassID" -> 44, "ChartAtSoft" -> {x -> -p, y -> p},
     "CanonicalFromPhysicalFactor" ->
      (2*eps^2*(-1 + y))/(-2 + 13*eps - 27*eps^2 + 18*eps^3),
     "EpsilonLeadingShift" -> 2,
     "SourceBoundaryOrders" -> Range[-1, 5],
     "RequiredLowerPhysicalOrders" -> Range[0, 3],
     "ExistingObservableOrders" -> Range[0, 2],
     "MissingObservableOrders" -> {3}|>
   },
 "ExactSupportProjection" -> <|
   "LowerPhysicalVectorOrder" -> {
     {"CF1", 1}, {"CF12", 4}, {"CF21", 1},
     {"CF199", 1}, {"CF199", 2}, {"CF53", 4}, {"CF53", 5}},
   "StateSelectorDimensions" -> {43, 7},
   "StateSelectorSparseTriples" ->
    {{1, 1, 1}, {2, 2, 1}, {12, 3, 1}, {21, 4, 1},
     {22, 5, 1}, {29, 6, 1}, {30, 7, 1}},
   "Convention" ->
    "F_source support = selector.diag(CanonicalFromPhysicalFactor).I_lower"|>,
 "NormalModeBlocks" -> {
   <|"ClassID" -> 1, "StateRows" -> {1},
     "NormalizedNormalResidue" -> {{-2}},
     "ConnectionExponents" -> {-2*eps}, "TangentialConnection" -> {{0}},
     "FunctionClass" -> "GPL", "PeriodID" -> None,
     "BoundaryRole" -> "ExactPhaseSpaceVolumeAnchor"|>,
   <|"ClassID" -> 5, "StateRows" -> {2},
     "NormalizedNormalResidue" -> {{0}},
     "ConnectionExponents" -> {0},
     "TangentialConnection" ->
      {{eps*(-4/p - 2/(p - 1) - 2/(p + 1))}},
     "FunctionClass" -> "GPL", "TangentialLetters" -> {0, 1, -1},
     "PeriodID" -> None,
     "BoundaryRole" -> "NoCandidateInNullityPeriods;PhysicalJetRealizationNotRecorded"|>,
   <|"ClassID" -> 17, "StateRows" -> {12},
     "NormalizedNormalResidue" -> {{0}},
     "ConnectionExponents" -> {0}, "TangentialConnection" -> {{0}},
     "FunctionClass" -> "GPL", "PeriodID" -> 6,
     "PeriodStatus" -> "KnownExactZeroForCF21Transfer",
     "ForcedSoftRatio" -> (2 - 3*eps)/(1 - 2*eps),
     "BoundaryRole" -> "Zero free mode; retain the volume-driven particular jets"|>,
   <|"ClassID" -> 44, "StateRows" -> {21, 22},
     "Realization" -> "CF199", "NormalizedNormalResidue" ->
      {{0, 0}, {-6, -4}},
     "ModeFrame" -> {{2, 0}, {-3, 1}},
     "ModeNames" -> {"PID9ZeroMode", "LambdaMinus4Mode"},
     "ConnectionExponents" -> {0, -4*eps},
     "TangentialConnectionInModeFrame" -> DiagonalMatrix[{
       eps*(-4/p - 2/(p - 1) - 2/(p + 1)),
       eps*(-4/p + 2/(p - 1) + 2/(p + 1))}],
     "FunctionClass" -> "GPL", "TangentialLetters" -> {0, 1, -1},
     "PeriodID" -> 9, "PeriodStatus" -> "FormalUnevaluated"|>,
   <|"ClassID" -> 44, "StateRows" -> {29, 30},
     "Realization" -> "CF53", "NormalizedNormalResidue" ->
      {{0, 0}, {-6, -4}},
     "ModeFrame" -> {{2, 0}, {-3, 1}},
     "ModeNames" -> {"PID9ZeroMode", "LambdaMinus4Mode"},
     "ConnectionExponents" -> {0, -4*eps},
     "TangentialConnectionInModeFrame" -> DiagonalMatrix[{
       eps*(-4/p - 2/(p - 1) - 2/(p + 1)),
       eps*(-4/p + 2/(p - 1) + 2/(p + 1))}],
     "FunctionClass" -> "GPL", "TangentialLetters" -> {0, 1, -1},
     "PeriodID" -> 9, "PeriodStatus" -> "FormalUnevaluated"|>
   },
 "MinimalWProjection" -> <|
   "FinalTargetRows" -> {44, 45}, "FinalEpsilonOrderWindow" -> {-4, 2},
   "AcceptedWOrderWindow" -> {-3, 6},
   "RequiredWOrdersByStateRows" -> <|
     {1, 2, 12} -> Range[-3, 2],
     {21, 22, 29, 30} -> Range[-3, 3]|>,
   "RequiredScalarWCoordinates" -> 92,
   "FormalPID9Projections" -> {
     <|"Realization" -> "CF199", "Formula" ->
       HoldForm[2*W[q][[All, 21]] - 3*W[q][[All, 22]]],
       "WOrders" -> Range[-3, 3]|>,
     <|"Realization" -> "CF53", "Formula" ->
       HoldForm[2*W[q][[All, 29]] - 3*W[q][[All, 30]]],
       "WOrders" -> Range[-3, 3]|>},
   "MaximumWPoleOrder" -> 2,
   "CanonicalSourceJetDepth" -> 2,
   "LowerPhysicalJetDepth" -> <|"CF1Row1" -> 3, "OtherRows" -> 2|>,
   "RequiredWLocalPowersForFiniteMatching" -> {-2, -1, 0},
   "ExistingEndpointABIProvides" -> {-2, -1},
   "MissingEndpointABIDatum" ->
    "Project the rho^0 coefficient before p reconstruction; do not reconstruct raw W"|>,
 "ObservableTransportInputs" -> {
   <|"Family" -> "CF1", "Status" -> "ExactObservableTransport",
     "CoefficientField" -> "Rational", "MaximumWeight" -> 6|>,
   <|"Family" -> "CF12", "Status" -> "ModularlyVerifiedObservableTransport",
     "CoefficientField" -> "Rational", "MaximumWeight" -> 5|>,
   <|"Family" -> "CF21", "Status" -> "ModularlyVerifiedObservableTransport",
     "CoefficientField" -> "Rational", "MaximumWeight" -> 7|>,
   <|"Family" -> "CF199", "Status" -> "ModularlyVerifiedObservableTransport",
     "CoefficientField" -> "Rational", "MaximumWeight" -> 5|>,
   <|"Family" -> "CF53", "Status" -> "ModularlyVerifiedObservableTransport",
     "CoefficientField" -> "Rational", "MaximumWeight" -> 6|>
   },
 "Stage3NeedsLedger" -> {
   <|"PeriodID" -> {"CF199", 9}, "PeriodClass" -> "GPL",
     "Family" -> "CF199", "Limit" -> "1-v-w -> 0 at v=p^2",
     "FrobeniusMode" -> <|"LocalEigenvalue" -> 0,
       "GeneralizedLevel" -> 0, "CanonicalBlockMode" -> {2, -3}|>,
     "AffectedStateRows" -> {21, 22},
     "AffectedBoundaryCoordinates" ->
      (BoundaryPeriodCoefficient[{"CF199", 9}, #] & /@ Range[-1, 5]),
     "DemandedOutputs" -> Flatten[Table[{order, row},
       {order, -4, 2}, {row, {44, 45}}], 1],
     "Status" -> "Unevaluated",
     "Problem" -> "No period_09 certificate or exact realization transfer"|>,
   <|"PeriodID" -> {"CF53", 9}, "PeriodClass" -> "GPL",
     "Family" -> "CF53", "Limit" -> "1-v-w -> 0 at v=p^2",
     "FrobeniusMode" -> <|"LocalEigenvalue" -> 0,
       "GeneralizedLevel" -> 0, "CanonicalBlockMode" -> {2, -3}|>,
     "AffectedStateRows" -> {29, 30},
     "AffectedBoundaryCoordinates" ->
      (BoundaryPeriodCoefficient[{"CF53", 9}, #] & /@ Range[-1, 5]),
     "DemandedOutputs" -> Flatten[Table[{order, row},
       {order, -4, 2}, {row, {44, 45}}], 1],
     "Status" -> "Unevaluated",
     "Problem" -> "No period_09 certificate or exact realization transfer"|>
   },
 "PrunedStage3Inputs" -> <|
   "KnownZero" -> {{"CF21", 6}},
   "Formal" -> {{"CF199", 9}, {"CF53", 9}},
   "Elliptic" -> {},
   "DoNotIdentifyAcrossFamilies" ->
    "Class sharing alone does not identify physical period coefficients"|>,
 "RemainingDataNeeds" -> {
   "Soft Frobenius jets through the listed depth for all five lower families",
   "One additional targeted observable epsilon order for CF12, CF199 and CF53",
   "The projected rho^0 W coefficient",
   "Evaluation or an exact realization transfer for the two PID9 zero modes"
   }
|>
