<|"Status" -> "CF303Sector19FrontierRootCensusPassedV1", "Family" -> "CF303", 
 "Sector" -> 19, "BlockRecords" -> 
  <|"Diagonal" -> <|"ScalarCount" -> 32, "NonzeroScalarCount" -> 30, 
     "SourceThirdRootScalarCount" -> 0, "ResidualOddScalarCount" -> 0, 
     "MappingSeconds" -> 0.|>, 18 -> <|"LowerSector" -> 18, 
     "LowerWidth" -> 2, "RightDiagonalScalarCount" -> 8, 
     "DirectForcingScalarCount" -> 16, "NonzeroScalarCount" -> 24, 
     "SourceThirdRootScalarCount" -> 0, "ResidualOddScalarCount" -> 0, 
     "MappingSeconds" -> 0.|>, 17 -> <|"LowerSector" -> 17, 
     "LowerWidth" -> 1, "RightDiagonalScalarCount" -> 2, 
     "DirectForcingScalarCount" -> 8, "NonzeroScalarCount" -> 2, 
     "SourceThirdRootScalarCount" -> 0, "ResidualOddScalarCount" -> 0, 
     "MappingSeconds" -> 0.|>, 16 -> <|"LowerSector" -> 16, 
     "LowerWidth" -> 2, "RightDiagonalScalarCount" -> 8, 
     "DirectForcingScalarCount" -> 16, "NonzeroScalarCount" -> 8, 
     "SourceThirdRootScalarCount" -> 0, "ResidualOddScalarCount" -> 0, 
     "MappingSeconds" -> 0.|>, 15 -> <|"LowerSector" -> 15, 
     "LowerWidth" -> 3, "RightDiagonalScalarCount" -> 18, 
     "DirectForcingScalarCount" -> 24, "NonzeroScalarCount" -> 18, 
     "SourceThirdRootScalarCount" -> 0, "ResidualOddScalarCount" -> 0, 
     "MappingSeconds" -> 0.|>, 14 -> <|"LowerSector" -> 14, 
     "LowerWidth" -> 2, "RightDiagonalScalarCount" -> 8, 
     "DirectForcingScalarCount" -> 16, "NonzeroScalarCount" -> 8, 
     "SourceThirdRootScalarCount" -> 0, "ResidualOddScalarCount" -> 0, 
     "MappingSeconds" -> 0.|>, 13 -> <|"LowerSector" -> 13, 
     "LowerWidth" -> 4, "RightDiagonalScalarCount" -> 32, 
     "DirectForcingScalarCount" -> 32, "NonzeroScalarCount" -> 32, 
     "SourceThirdRootScalarCount" -> 0, "ResidualOddScalarCount" -> 0, 
     "MappingSeconds" -> 0.|>, 12 -> <|"LowerSector" -> 12, 
     "LowerWidth" -> 4, "RightDiagonalScalarCount" -> 32, 
     "DirectForcingScalarCount" -> 32, "NonzeroScalarCount" -> 63, 
     "SourceThirdRootScalarCount" -> 0, "ResidualOddScalarCount" -> 0, 
     "MappingSeconds" -> 0.|>, 11 -> <|"LowerSector" -> 11, 
     "LowerWidth" -> 1, "RightDiagonalScalarCount" -> 2, 
     "DirectForcingScalarCount" -> 8, "NonzeroScalarCount" -> 10, 
     "SourceThirdRootScalarCount" -> 0, "ResidualOddScalarCount" -> 0, 
     "MappingSeconds" -> 0.|>, 10 -> <|"LowerSector" -> 10, 
     "LowerWidth" -> 1, "RightDiagonalScalarCount" -> 2, 
     "DirectForcingScalarCount" -> 8, "NonzeroScalarCount" -> 1, 
     "SourceThirdRootScalarCount" -> 0, "ResidualOddScalarCount" -> 0, 
     "MappingSeconds" -> 0.|>, 9 -> <|"LowerSector" -> 9, "LowerWidth" -> 1, 
     "RightDiagonalScalarCount" -> 2, "DirectForcingScalarCount" -> 8, 
     "NonzeroScalarCount" -> 2, "SourceThirdRootScalarCount" -> 0, 
     "ResidualOddScalarCount" -> 0, "MappingSeconds" -> 0.|>, 
   8 -> <|"LowerSector" -> 8, "LowerWidth" -> 1, 
     "RightDiagonalScalarCount" -> 2, "DirectForcingScalarCount" -> 8, 
     "NonzeroScalarCount" -> 1, "SourceThirdRootScalarCount" -> 0, 
     "ResidualOddScalarCount" -> 0, "MappingSeconds" -> 0.|>, 
   7 -> <|"LowerSector" -> 7, "LowerWidth" -> 2, 
     "RightDiagonalScalarCount" -> 8, "DirectForcingScalarCount" -> 16, 
     "NonzeroScalarCount" -> 8, "SourceThirdRootScalarCount" -> 0, 
     "ResidualOddScalarCount" -> 0, "MappingSeconds" -> 0.|>, 
   6 -> <|"LowerSector" -> 6, "LowerWidth" -> 1, 
     "RightDiagonalScalarCount" -> 2, "DirectForcingScalarCount" -> 8, 
     "NonzeroScalarCount" -> 10, "SourceThirdRootScalarCount" -> 0, 
     "ResidualOddScalarCount" -> 0, "MappingSeconds" -> 0.|>, 
   5 -> <|"LowerSector" -> 5, "LowerWidth" -> 1, 
     "RightDiagonalScalarCount" -> 2, "DirectForcingScalarCount" -> 8, 
     "NonzeroScalarCount" -> 2, "SourceThirdRootScalarCount" -> 0, 
     "ResidualOddScalarCount" -> 0, "MappingSeconds" -> 0.|>, 
   4 -> <|"LowerSector" -> 4, "LowerWidth" -> 1, 
     "RightDiagonalScalarCount" -> 2, "DirectForcingScalarCount" -> 8, 
     "NonzeroScalarCount" -> 2, "SourceThirdRootScalarCount" -> 0, 
     "ResidualOddScalarCount" -> 0, "MappingSeconds" -> 0.|>, 
   3 -> <|"LowerSector" -> 3, "LowerWidth" -> 1, 
     "RightDiagonalScalarCount" -> 2, "DirectForcingScalarCount" -> 8, 
     "NonzeroScalarCount" -> 2, "SourceThirdRootScalarCount" -> 0, 
     "ResidualOddScalarCount" -> 0, "MappingSeconds" -> 0.|>, 
   2 -> <|"LowerSector" -> 2, "LowerWidth" -> 1, 
     "RightDiagonalScalarCount" -> 2, "DirectForcingScalarCount" -> 8, 
     "NonzeroScalarCount" -> 2, "SourceThirdRootScalarCount" -> 0, 
     "ResidualOddScalarCount" -> 0, "MappingSeconds" -> 0.|>, 
   1 -> <|"LowerSector" -> 1, "LowerWidth" -> 1, 
     "RightDiagonalScalarCount" -> 2, "DirectForcingScalarCount" -> 8, 
     "NonzeroScalarCount" -> 10, "SourceThirdRootScalarCount" -> 0, 
     "ResidualOddScalarCount" -> 0, "MappingSeconds" -> 0.|>|>, 
 "ScalarRecords" -> {<|"Label" -> "E/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {1}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 1452, "CanonicalSourceLeafCount" -> 
     1373, "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/1,2", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "E/1/1,3", "LiteralZero" -> False, 
    "SourceRootIndices" -> {1}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 489, "CanonicalSourceLeafCount" -> 
     489, "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/1,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 817, "CanonicalSourceLeafCount" -> 817, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3632, "CanonicalSourceLeafCount" -> 3632, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2420, "CanonicalSourceLeafCount" -> 2311, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/2,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2305, "CanonicalSourceLeafCount" -> 2202, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/2,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3331, "CanonicalSourceLeafCount" -> 3175, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 4136, "CanonicalSourceLeafCount" -> 4136, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2420, "CanonicalSourceLeafCount" -> 2311, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/3,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2716, "CanonicalSourceLeafCount" -> 2592, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/3,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3335, "CanonicalSourceLeafCount" -> 3178, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3178, "CanonicalSourceLeafCount" -> 3178, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/4,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2058, "CanonicalSourceLeafCount" -> 1967, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/4,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2291, "CanonicalSourceLeafCount" -> 2183, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/1/4,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2831, "CanonicalSourceLeafCount" -> 2701, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 1678, "CanonicalSourceLeafCount" -> 1582, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/1,2", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "E/2/1,3", "LiteralZero" -> False, 
    "SourceRootIndices" -> {1}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 647, "CanonicalSourceLeafCount" -> 
     650, "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/1,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 956, "CanonicalSourceLeafCount" -> 954, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3514, "CanonicalSourceLeafCount" -> 3514, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2698, "CanonicalSourceLeafCount" -> 2576, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/2,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2300, "CanonicalSourceLeafCount" -> 2193, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/2,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2958, "CanonicalSourceLeafCount" -> 2817, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 4393, "CanonicalSourceLeafCount" -> 4393, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2784, "CanonicalSourceLeafCount" -> 2656, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/3,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2925, "CanonicalSourceLeafCount" -> 2785, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/3,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3707, "CanonicalSourceLeafCount" -> 3531, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3306, "CanonicalSourceLeafCount" -> 3306, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/4,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2316, "CanonicalSourceLeafCount" -> 2214, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/4,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 2506, "CanonicalSourceLeafCount" -> 2393, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "E/2/4,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3239, "CanonicalSourceLeafCount" -> 3087, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/18/1/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/18/1/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/18/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 14, "CanonicalSourceLeafCount" -> 14, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/18/1/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 25, "CanonicalSourceLeafCount" -> 18, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/18/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/18/2/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/18/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 8, "CanonicalSourceLeafCount" -> 8, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/18/2/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 41, "CanonicalSourceLeafCount" -> 32, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/1/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 46, "CanonicalSourceLeafCount" -> 46, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/1/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 56, "CanonicalSourceLeafCount" -> 56, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3955, "CanonicalSourceLeafCount" -> 3950, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/1/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3963, "CanonicalSourceLeafCount" -> 3961, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/1/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 4204, "CanonicalSourceLeafCount" -> 4207, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/1/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 4220, "CanonicalSourceLeafCount" -> 4218, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/1/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3386, "CanonicalSourceLeafCount" -> 3385, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/1/4,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3398, "CanonicalSourceLeafCount" -> 3396, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 63, "CanonicalSourceLeafCount" -> 63, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/2/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 57, "CanonicalSourceLeafCount" -> 57, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 4684, "CanonicalSourceLeafCount" -> 4680, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/2/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5740, "CanonicalSourceLeafCount" -> 5740, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/2/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5070, "CanonicalSourceLeafCount" -> 5068, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/2/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5851, "CanonicalSourceLeafCount" -> 5851, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/2/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 4123, "CanonicalSourceLeafCount" -> 4121, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/18/2/4,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5035, "CanonicalSourceLeafCount" -> 5035, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/17/1/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 21, "CanonicalSourceLeafCount" -> 15, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/17/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 21, "CanonicalSourceLeafCount" -> 15, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/17/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/17/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/17/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/17/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/17/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/17/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/17/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/17/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/16/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 23, "CanonicalSourceLeafCount" -> 
     17, "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/16/1/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 9, "CanonicalSourceLeafCount" -> 9, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/16/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 19, "CanonicalSourceLeafCount" -> 19, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/16/1/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 24, "CanonicalSourceLeafCount" -> 19, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/16/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 24, "CanonicalSourceLeafCount" -> 19, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/16/2/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 13, "CanonicalSourceLeafCount" -> 13, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/16/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 19, "CanonicalSourceLeafCount" -> 19, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/16/2/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 19, "CanonicalSourceLeafCount" -> 19, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/16/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/16/1/1,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/1/2,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/1/3,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/1/4,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/2/1,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/2/2,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/2/3,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/16/2/4,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/15/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {2}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 903, "CanonicalSourceLeafCount" -> 
     847, "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/1/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 249, "CanonicalSourceLeafCount" -> 239, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/1/1,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 84, "CanonicalSourceLeafCount" -> 85, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 361, "CanonicalSourceLeafCount" -> 343, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/1/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 637, "CanonicalSourceLeafCount" -> 602, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/1/2,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 177, "CanonicalSourceLeafCount" -> 177, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/1/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 362, "CanonicalSourceLeafCount" -> 345, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/1/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 323, "CanonicalSourceLeafCount" -> 309, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/1/3,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 134, "CanonicalSourceLeafCount" -> 120, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 858, "CanonicalSourceLeafCount" -> 810, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/2/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 353, "CanonicalSourceLeafCount" -> 336, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/2/1,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 176, "CanonicalSourceLeafCount" -> 176, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 360, "CanonicalSourceLeafCount" -> 344, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/2/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 852, "CanonicalSourceLeafCount" -> 802, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/2/2,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 175, "CanonicalSourceLeafCount" -> 177, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/2/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 285, "CanonicalSourceLeafCount" -> 274, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/2/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 284, "CanonicalSourceLeafCount" -> 273, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/15/2/3,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {2}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 67, "CanonicalSourceLeafCount" -> 67, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/15/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/15/1/1,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/1/1,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/1/2,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/1/2,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/1/3,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/1/3,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/1/4,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/1/4,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/1,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/1,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/2,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/2,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/3,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/3,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/4,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/15/2/4,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/14/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/14/1/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/14/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 8, "CanonicalSourceLeafCount" -> 8, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/14/1/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 33, "CanonicalSourceLeafCount" -> 32, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/14/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/14/2/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/14/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 14, "CanonicalSourceLeafCount" -> 14, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/14/2/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 17, "CanonicalSourceLeafCount" -> 18, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/14/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/14/1/1,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/1/2,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/1/3,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/1/4,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/2/1,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/2/2,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/2/3,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/14/2/4,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/13/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {1}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 
     644, "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/1,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/1,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/2,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/2,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/3,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/3,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/4,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/4,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/1/4,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 644, "CanonicalSourceLeafCount" -> 644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/1,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/1,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/2,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/2,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/3,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/3,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/4,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/4,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/13/2/4,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 649, "CanonicalSourceLeafCount" -> 649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/13/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/13/1/1,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/1,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/1,4", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/2,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/2,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/2,4", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/3,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/3,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/3,4", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/4,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/4,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/1/4,4", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/1,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/1,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/1,4", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/2,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/2,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/2,4", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/3,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/3,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/3,4", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/4,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/4,3", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/13/2/4,4", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/12/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {1}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 460, "CanonicalSourceLeafCount" -> 
     460, "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 151, "CanonicalSourceLeafCount" -> 151, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/1,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 152, "CanonicalSourceLeafCount" -> 152, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/1,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 148, "CanonicalSourceLeafCount" -> 148, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 128, "CanonicalSourceLeafCount" -> 128, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 14, "CanonicalSourceLeafCount" -> 14, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/2,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 14, "CanonicalSourceLeafCount" -> 14, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/2,4", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "C/12/1/3,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {1}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 128, "CanonicalSourceLeafCount" -> 
     128, "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 7, "CanonicalSourceLeafCount" -> 7, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/3,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 15, "CanonicalSourceLeafCount" -> 15, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/3,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 7, "CanonicalSourceLeafCount" -> 7, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 129, "CanonicalSourceLeafCount" -> 129, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/4,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/4,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3, "CanonicalSourceLeafCount" -> 3, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/1/4,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 317, "CanonicalSourceLeafCount" -> 317, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 148, "CanonicalSourceLeafCount" -> 148, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/1,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 151, "CanonicalSourceLeafCount" -> 151, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/1,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 150, "CanonicalSourceLeafCount" -> 150, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 131, "CanonicalSourceLeafCount" -> 131, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 19, "CanonicalSourceLeafCount" -> 19, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/2,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 17, "CanonicalSourceLeafCount" -> 17, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/2,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 131, "CanonicalSourceLeafCount" -> 131, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 7, "CanonicalSourceLeafCount" -> 7, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/3,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 11, "CanonicalSourceLeafCount" -> 11, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/3,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 14, "CanonicalSourceLeafCount" -> 14, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 129, "CanonicalSourceLeafCount" -> 129, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/4,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 7, "CanonicalSourceLeafCount" -> 7, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/4,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/12/2/4,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 174, "CanonicalSourceLeafCount" -> 174, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 196, "CanonicalSourceLeafCount" -> 196, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/1,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 143, "CanonicalSourceLeafCount" -> 143, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/1,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 219, "CanonicalSourceLeafCount" -> 219, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 4060, "CanonicalSourceLeafCount" -> 4072, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 16443, "CanonicalSourceLeafCount" -> 16445, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/2,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 14367, "CanonicalSourceLeafCount" -> 14367, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/2,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 11951, "CanonicalSourceLeafCount" -> 11949, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 4215, "CanonicalSourceLeafCount" -> 4215, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 16644, "CanonicalSourceLeafCount" -> 16644, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/3,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 14650, "CanonicalSourceLeafCount" -> 14649, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/3,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 12280, "CanonicalSourceLeafCount" -> 12280, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 3496, "CanonicalSourceLeafCount" -> 3491, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/4,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 14354, "CanonicalSourceLeafCount" -> 14354, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/4,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 12489, "CanonicalSourceLeafCount" -> 12491, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/1/4,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 10336, "CanonicalSourceLeafCount" -> 10336, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 167, "CanonicalSourceLeafCount" -> 167, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 331, "CanonicalSourceLeafCount" -> 331, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/1,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 235, "CanonicalSourceLeafCount" -> 235, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/1,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 235, "CanonicalSourceLeafCount" -> 235, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5510, "CanonicalSourceLeafCount" -> 4865, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 18135, "CanonicalSourceLeafCount" -> 18136, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/2,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 16201, "CanonicalSourceLeafCount" -> 16200, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/2,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 13503, "CanonicalSourceLeafCount" -> 13500, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5510, "CanonicalSourceLeafCount" -> 4867, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/3,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 18276, "CanonicalSourceLeafCount" -> 18276, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/3,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 16325, "CanonicalSourceLeafCount" -> 16325, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/3,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 13815, "CanonicalSourceLeafCount" -> 13815, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 4692, "CanonicalSourceLeafCount" -> 4151, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/4,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 15898, "CanonicalSourceLeafCount" -> 15898, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/4,3", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 14125, "CanonicalSourceLeafCount" -> 14125, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/12/2/4,4", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 11899, "CanonicalSourceLeafCount" -> 11899, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/11/1/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 7, "CanonicalSourceLeafCount" -> 9, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/11/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 7, "CanonicalSourceLeafCount" -> 9, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/11/1/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 663, "CanonicalSourceLeafCount" -> 4427, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/11/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 47681, "CanonicalSourceLeafCount" -> 38443, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/11/1/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 48806, "CanonicalSourceLeafCount" -> 38751, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/11/1/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 41326, "CanonicalSourceLeafCount" -> 34133, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/11/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 994, "CanonicalSourceLeafCount" -> 4613, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/11/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 54917, "CanonicalSourceLeafCount" -> 42264, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/11/2/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 55723, "CanonicalSourceLeafCount" -> 42520, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/11/2/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 48031, "CanonicalSourceLeafCount" -> 37640, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/10/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "C/10/2/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/10/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/10/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/10/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/10/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/10/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/10/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/10/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/10/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/9/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/9/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/9/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/9/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/9/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/9/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/9/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/9/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/9/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/9/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/8/1/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/8/2/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 15, "CanonicalSourceLeafCount" -> 
     14, "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/8/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/8/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/8/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/8/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/8/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/8/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/8/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/8/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/7/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 17, "CanonicalSourceLeafCount" -> 
     17, "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/7/1/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 9, "CanonicalSourceLeafCount" -> 9, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/7/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 7, "CanonicalSourceLeafCount" -> 7, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/7/1/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 39, "CanonicalSourceLeafCount" -> 38, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/7/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 19, "CanonicalSourceLeafCount" -> 19, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/7/2/1,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 9, "CanonicalSourceLeafCount" -> 9, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/7/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 7, "CanonicalSourceLeafCount" -> 7, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/7/2/2,2", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 39, "CanonicalSourceLeafCount" -> 39, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/7/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/7/1/1,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/1/2,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/1/3,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/1/4,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/2/1,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/2/2,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/2/3,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/7/2/4,2", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/6/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/6/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 7, "CanonicalSourceLeafCount" -> 7, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/6/1/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 702, "CanonicalSourceLeafCount" -> 4451, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/6/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 47488, "CanonicalSourceLeafCount" -> 38416, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/6/1/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 48462, "CanonicalSourceLeafCount" -> 38750, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/6/1/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 41190, "CanonicalSourceLeafCount" -> 34133, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/6/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 955, "CanonicalSourceLeafCount" -> 4762, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/6/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 54566, "CanonicalSourceLeafCount" -> 42324, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/6/2/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 55132, "CanonicalSourceLeafCount" -> 42519, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/6/2/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 47683, "CanonicalSourceLeafCount" -> 37583, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/5/1/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 13, "CanonicalSourceLeafCount" -> 14, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/5/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/5/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/5/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/5/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/5/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/5/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/5/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/5/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/5/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/4/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 19, "CanonicalSourceLeafCount" -> 
     16, "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/4/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 17, "CanonicalSourceLeafCount" -> 18, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/4/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/4/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/4/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/4/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/4/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/4/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/4/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/4/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/3/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/3/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/3/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/3/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/3/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/3/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/3/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/3/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/3/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/3/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/2/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/2/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 5, "CanonicalSourceLeafCount" -> 5, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/2/1/1,1", 
    "LiteralZero" -> True, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0.|>, 
   <|"Label" -> "B/2/1/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/2/1/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/2/1/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/2/2/1,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/2/2/2,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/2/2/3,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "B/2/2/4,1", "LiteralZero" -> True, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0.|>, <|"Label" -> "C/1/1/1,1", "LiteralZero" -> False, 
    "SourceRootIndices" -> {}, "ResidualOddChannelZero" -> True, 
    "Seconds" -> 0., "SourceLeafCount" -> 8, "CanonicalSourceLeafCount" -> 8, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "C/1/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 8, "CanonicalSourceLeafCount" -> 8, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/1/1/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 1009, "CanonicalSourceLeafCount" -> 4451, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/1/1/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 73097, "CanonicalSourceLeafCount" -> 38486, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/1/1/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 74516, "CanonicalSourceLeafCount" -> 38753, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/1/1/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 63273, "CanonicalSourceLeafCount" -> 34133, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/1/2/1,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 1589, "CanonicalSourceLeafCount" -> 4771, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/1/2/2,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 83347, "CanonicalSourceLeafCount" -> 42327, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/1/2/3,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 84418, "CanonicalSourceLeafCount" -> 42522, 
    "ResidualChannelLeafCounts" -> {}|>, <|"Label" -> "B/1/2/4,1", 
    "LiteralZero" -> False, "SourceRootIndices" -> {1}, 
    "ResidualOddChannelZero" -> True, "Seconds" -> 0., 
    "SourceLeafCount" -> 73038, "CanonicalSourceLeafCount" -> 37676, 
    "ResidualChannelLeafCounts" -> {}|>}, 
 "InputHashes" -> 
  <|"/home/maxzhang/factorization-and-loops/Addon/Load/LoadFACET.wl" -> 
    "fa6f10b2c971b6016d4955feeffeb7597659a5d86f86ad0829ba95136d81eb7e", 
   "/home/maxzhang/factorization-and-loops/FeynFacet/Private/MultiquadraticSt\
ripSolve.wl" -> 
    "5c3493d02636cf51151baae47128d77a959f880a2e1b36dd4f8077598710dc09", 
   "/tmp/codex-triple-root-20260824-pairchart.jnlBfZ/cf303_resume_from_sector\
16_v1/sector_state_CF303_identity_capture_xh_v4.wl" -> 
    "1454906ac674090664e0065732881b2cd8409a15c2f670ca61fd05b5a7d4de06", 
   "/tmp/codex-triple-root-20260824-pairchart.jnlBfZ/cf303_17_12_pair_factor_\
audit_v3/chart_factor_bundle.wl" -> 
    "8dccaff196948ffadb354370fac3b59c5e84e297886eec179e3e5328ff30a1ec"|>, 
 "PackageSourceModified" -> False, "Created" -> "2026-08-24T04:26:16"|>
